/*
 * Decompiled with CFR 0.150.
 */
package net.minecraft.aA;

import net.minecraft.aA.m;
import net.minecraft.aA.t;

public class n {
    public final /* synthetic */ int aj;
    public final /* synthetic */ int u;
    public final /* synthetic */ float aA;
    public final /* synthetic */ int av;
    public final /* synthetic */ int N;
    public final /* synthetic */ int o;
    public final /* synthetic */ boolean au;
    public final /* synthetic */ int n;
    public final /* synthetic */ int as;
    public final /* synthetic */ int F;
    public final /* synthetic */ boolean a;
    public final /* synthetic */ int am;
    public final /* synthetic */ float ad;
    public final /* synthetic */ int T;
    public final /* synthetic */ int f;
    public final /* synthetic */ boolean ay;
    public final /* synthetic */ int af;
    public final /* synthetic */ int m;
    public final /* synthetic */ boolean ac;
    public final /* synthetic */ boolean l;
    public final /* synthetic */ int c;
    public final /* synthetic */ int e;
    public final /* synthetic */ int G;
    public final /* synthetic */ int h;
    public final /* synthetic */ boolean q;
    public final /* synthetic */ int s;
    public final /* synthetic */ float Z;
    public final /* synthetic */ boolean ai;
    public final /* synthetic */ int z;
    public final /* synthetic */ boolean R;
    public final /* synthetic */ boolean w;
    public final /* synthetic */ int ax;
    public final /* synthetic */ int L;
    public final /* synthetic */ float V;
    public final /* synthetic */ float x;
    public final /* synthetic */ int an;
    public final /* synthetic */ int P;
    public final /* synthetic */ int t;
    public final /* synthetic */ float b;
    public final /* synthetic */ int k;
    public final /* synthetic */ int J;
    public final /* synthetic */ int ar;
    public final /* synthetic */ int aa;
    public final /* synthetic */ int g;
    public final /* synthetic */ float K;
    public final /* synthetic */ float Y;
    public final /* synthetic */ int C;
    public final /* synthetic */ int r;
    public final /* synthetic */ int U;
    public final /* synthetic */ int az;
    public final /* synthetic */ float B;
    public final /* synthetic */ int O;
    public final /* synthetic */ int al;
    public final /* synthetic */ int ao;
    public final /* synthetic */ int Q;
    public final /* synthetic */ float ak;
    public final /* synthetic */ boolean p;
    public final /* synthetic */ float aw;
    public final /* synthetic */ int D;
    public final /* synthetic */ int i;
    public final /* synthetic */ float W;
    public final /* synthetic */ int d;
    public final /* synthetic */ int at;
    public final /* synthetic */ int aq;
    public final /* synthetic */ float ap;
    public final /* synthetic */ int I;
    public final /* synthetic */ boolean H;
    public final /* synthetic */ int A;
    public final /* synthetic */ int S;
    public final /* synthetic */ int ag;
    public final /* synthetic */ float X;
    public final /* synthetic */ boolean j;
    public final /* synthetic */ float ab;
    public final /* synthetic */ int M;
    public final /* synthetic */ int ae;
    public final /* synthetic */ int E;
    public final /* synthetic */ int y;
    public final /* synthetic */ float ah;
    public final /* synthetic */ int v;

    private n(t t2) {
        this.W = t2.L;
        this.ad = t2.I;
        this.Z = t2.Z;
        this.x = t2.S;
        this.ak = t2.l;
        this.V = t2.ak;
        this.aA = t2.aB;
        this.ab = t2.R;
        this.B = t2.aw;
        this.Y = t2.ac;
        this.ah = t2.M;
        this.X = t2.v;
        this.aw = t2.J;
        this.b = t2.ab;
        this.K = t2.D;
        this.ap = t2.aa;
        this.am = t2.ah;
        this.ay = t2.f;
        this.ac = t2.K;
        this.at = t2.Y;
        this.l = t2.ar;
        this.ai = t2.O;
        this.p = t2.Q;
        this.au = t2.aA;
        this.q = t2.h;
        this.H = t2.ao;
        this.j = t2.p;
        this.a = t2.am;
        this.ao = t2.ad;
        this.w = t2.W;
        this.L = t2.a;
        this.R = t2.c;
        this.d = t2.j;
        this.z = t2.B;
        this.aa = t2.r;
        this.n = t2.i;
        this.an = t2.X;
        this.ar = t2.az;
        this.E = t2.s;
        this.N = t2.d;
        this.U = t2.q;
        this.as = t2.ai;
        this.A = t2.ay;
        this.o = t2.E;
        this.g = t2.w;
        this.r = t2.o;
        this.M = t2.ag;
        this.t = t2.al;
        this.S = t2.V;
        this.af = t2.G;
        this.az = t2.U;
        this.J = t2.aj;
        this.G = t2.t;
        this.f = t2.u;
        this.D = t2.g;
        this.k = t2.ax;
        this.Q = t2.F;
        this.I = t2.av;
        this.c = t2.k;
        this.aq = t2.N;
        this.h = t2.ap;
        this.ax = t2.as;
        this.F = t2.P;
        this.v = t2.m;
        this.ag = t2.at;
        this.s = t2.n;
        this.al = t2.au;
        this.aj = t2.e;
        this.i = t2.y;
        this.C = t2.af;
        this.e = t2.C;
        this.m = t2.ae;
        this.P = t2.T;
        this.y = t2.x;
        this.T = t2.aq;
        this.u = t2.an;
        this.av = t2.H;
        this.ae = t2.b;
        this.O = t2.A;
    }

    n(t t2, m m2) {
        this(t2);
    }
}

