/*
 * Decompiled with CFR 0.150.
 */
package net.minecraft.r;

import net.minecraft.P.r;
import net.minecraft.av.a;
import net.minecraft.r.m;

public class F
implements a {
    private static final /* synthetic */ String[] a;

    @Override
    public int a() {
        return 102;
    }

    private static gP a(gP gP2) {
        return gP2;
    }

    static {
        a = new String[2268];
        F.a[1] = "minecraft:stone";
        F.a[2] = "minecraft:grass";
        F.a[3] = "minecraft:dirt";
        F.a[4] = "minecraft:cobblestone";
        F.a[5] = "minecraft:planks";
        F.a[6] = "minecraft:sapling";
        F.a[7] = "minecraft:bedrock";
        F.a[8] = "minecraft:flowing_water";
        F.a[9] = "minecraft:water";
        F.a[10] = "minecraft:flowing_lava";
        F.a[11] = "minecraft:lava";
        F.a[12] = "minecraft:sand";
        F.a[13] = "minecraft:gravel";
        F.a[14] = "minecraft:gold_ore";
        F.a[15] = "minecraft:iron_ore";
        F.a[16] = "minecraft:coal_ore";
        F.a[17] = "minecraft:log";
        F.a[18] = "minecraft:leaves";
        F.a[19] = "minecraft:sponge";
        F.a[20] = "minecraft:glass";
        F.a[21] = "minecraft:lapis_ore";
        F.a[22] = "minecraft:lapis_block";
        F.a[23] = "minecraft:dispenser";
        F.a[24] = "minecraft:sandstone";
        F.a[25] = "minecraft:noteblock";
        F.a[27] = "minecraft:golden_rail";
        F.a[28] = "minecraft:detector_rail";
        F.a[29] = "minecraft:sticky_piston";
        F.a[30] = "minecraft:web";
        F.a[31] = "minecraft:tallgrass";
        F.a[32] = "minecraft:deadbush";
        F.a[33] = "minecraft:piston";
        F.a[35] = "minecraft:wool";
        F.a[37] = "minecraft:yellow_flower";
        F.a[38] = "minecraft:red_flower";
        F.a[39] = "minecraft:brown_mushroom";
        F.a[40] = "minecraft:red_mushroom";
        F.a[41] = "minecraft:gold_block";
        F.a[42] = "minecraft:iron_block";
        F.a[43] = "minecraft:double_stone_slab";
        F.a[44] = "minecraft:stone_slab";
        F.a[45] = "minecraft:brick_block";
        F.a[46] = "minecraft:tnt";
        F.a[47] = "minecraft:bookshelf";
        F.a[48] = "minecraft:mossy_cobblestone";
        F.a[49] = "minecraft:obsidian";
        F.a[50] = "minecraft:torch";
        F.a[51] = "minecraft:fire";
        F.a[52] = "minecraft:mob_spawner";
        F.a[53] = "minecraft:oak_stairs";
        F.a[54] = "minecraft:chest";
        F.a[56] = "minecraft:diamond_ore";
        F.a[57] = "minecraft:diamond_block";
        F.a[58] = "minecraft:crafting_table";
        F.a[60] = "minecraft:farmland";
        F.a[61] = "minecraft:furnace";
        F.a[62] = "minecraft:lit_furnace";
        F.a[65] = "minecraft:ladder";
        F.a[66] = "minecraft:rail";
        F.a[67] = "minecraft:stone_stairs";
        F.a[69] = "minecraft:lever";
        F.a[70] = "minecraft:stone_pressure_plate";
        F.a[72] = "minecraft:wooden_pressure_plate";
        F.a[73] = "minecraft:redstone_ore";
        F.a[76] = "minecraft:redstone_torch";
        F.a[77] = "minecraft:stone_button";
        F.a[78] = "minecraft:snow_layer";
        F.a[79] = "minecraft:ice";
        F.a[80] = "minecraft:snow";
        F.a[81] = "minecraft:cactus";
        F.a[82] = "minecraft:clay";
        F.a[84] = "minecraft:jukebox";
        F.a[85] = "minecraft:fence";
        F.a[86] = "minecraft:pumpkin";
        F.a[87] = "minecraft:netherrack";
        F.a[88] = "minecraft:soul_sand";
        F.a[89] = "minecraft:glowstone";
        F.a[90] = "minecraft:portal";
        F.a[91] = "minecraft:lit_pumpkin";
        F.a[95] = "minecraft:stained_glass";
        F.a[96] = "minecraft:trapdoor";
        F.a[97] = "minecraft:monster_egg";
        F.a[98] = "minecraft:stonebrick";
        F.a[99] = "minecraft:brown_mushroom_block";
        F.a[100] = "minecraft:red_mushroom_block";
        F.a[101] = "minecraft:iron_bars";
        F.a[102] = "minecraft:glass_pane";
        F.a[103] = "minecraft:melon_block";
        F.a[106] = "minecraft:vine";
        F.a[107] = "minecraft:fence_gate";
        F.a[108] = "minecraft:brick_stairs";
        F.a[109] = "minecraft:stone_brick_stairs";
        F.a[110] = "minecraft:mycelium";
        F.a[111] = "minecraft:waterlily";
        F.a[112] = "minecraft:nether_brick";
        F.a[113] = "minecraft:nether_brick_fence";
        F.a[114] = "minecraft:nether_brick_stairs";
        F.a[116] = "minecraft:enchanting_table";
        F.a[119] = "minecraft:end_portal";
        F.a[120] = "minecraft:end_portal_frame";
        F.a[121] = "minecraft:end_stone";
        F.a[122] = "minecraft:dragon_egg";
        F.a[123] = "minecraft:redstone_lamp";
        F.a[125] = "minecraft:double_wooden_slab";
        F.a[126] = "minecraft:wooden_slab";
        F.a[127] = "minecraft:cocoa";
        F.a[128] = "minecraft:sandstone_stairs";
        F.a[129] = "minecraft:emerald_ore";
        F.a[130] = "minecraft:ender_chest";
        F.a[131] = "minecraft:tripwire_hook";
        F.a[133] = "minecraft:emerald_block";
        F.a[134] = "minecraft:spruce_stairs";
        F.a[135] = "minecraft:birch_stairs";
        F.a[136] = "minecraft:jungle_stairs";
        F.a[137] = "minecraft:command_block";
        F.a[138] = "minecraft:beacon";
        F.a[139] = "minecraft:cobblestone_wall";
        F.a[141] = "minecraft:carrots";
        F.a[142] = "minecraft:potatoes";
        F.a[143] = "minecraft:wooden_button";
        F.a[145] = "minecraft:anvil";
        F.a[146] = "minecraft:trapped_chest";
        F.a[147] = "minecraft:light_weighted_pressure_plate";
        F.a[148] = "minecraft:heavy_weighted_pressure_plate";
        F.a[151] = "minecraft:daylight_detector";
        F.a[152] = "minecraft:redstone_block";
        F.a[153] = "minecraft:quartz_ore";
        F.a[154] = "minecraft:hopper";
        F.a[155] = "minecraft:quartz_block";
        F.a[156] = "minecraft:quartz_stairs";
        F.a[157] = "minecraft:activator_rail";
        F.a[158] = "minecraft:dropper";
        F.a[159] = "minecraft:stained_hardened_clay";
        F.a[160] = "minecraft:stained_glass_pane";
        F.a[161] = "minecraft:leaves2";
        F.a[162] = "minecraft:log2";
        F.a[163] = "minecraft:acacia_stairs";
        F.a[164] = "minecraft:dark_oak_stairs";
        F.a[170] = "minecraft:hay_block";
        F.a[171] = "minecraft:carpet";
        F.a[172] = "minecraft:hardened_clay";
        F.a[173] = "minecraft:coal_block";
        F.a[174] = "minecraft:packed_ice";
        F.a[175] = "minecraft:double_plant";
        F.a[256] = "minecraft:iron_shovel";
        F.a[257] = "minecraft:iron_pickaxe";
        F.a[258] = "minecraft:iron_axe";
        F.a[259] = "minecraft:flint_and_steel";
        F.a[260] = "minecraft:apple";
        F.a[261] = "minecraft:bow";
        F.a[262] = "minecraft:arrow";
        F.a[263] = "minecraft:coal";
        F.a[264] = "minecraft:diamond";
        F.a[265] = "minecraft:iron_ingot";
        F.a[266] = "minecraft:gold_ingot";
        F.a[267] = "minecraft:iron_sword";
        F.a[268] = "minecraft:wooden_sword";
        F.a[269] = "minecraft:wooden_shovel";
        F.a[270] = "minecraft:wooden_pickaxe";
        F.a[271] = "minecraft:wooden_axe";
        F.a[272] = "minecraft:stone_sword";
        F.a[273] = "minecraft:stone_shovel";
        F.a[274] = "minecraft:stone_pickaxe";
        F.a[275] = "minecraft:stone_axe";
        F.a[276] = "minecraft:diamond_sword";
        F.a[277] = "minecraft:diamond_shovel";
        F.a[278] = "minecraft:diamond_pickaxe";
        F.a[279] = "minecraft:diamond_axe";
        F.a[280] = "minecraft:stick";
        F.a[281] = "minecraft:bowl";
        F.a[282] = "minecraft:mushroom_stew";
        F.a[283] = "minecraft:golden_sword";
        F.a[284] = "minecraft:golden_shovel";
        F.a[285] = "minecraft:golden_pickaxe";
        F.a[286] = "minecraft:golden_axe";
        F.a[287] = "minecraft:string";
        F.a[288] = "minecraft:feather";
        F.a[289] = "minecraft:gunpowder";
        F.a[290] = "minecraft:wooden_hoe";
        F.a[291] = "minecraft:stone_hoe";
        F.a[292] = "minecraft:iron_hoe";
        F.a[293] = "minecraft:diamond_hoe";
        F.a[294] = "minecraft:golden_hoe";
        F.a[295] = "minecraft:wheat_seeds";
        F.a[296] = "minecraft:wheat";
        F.a[297] = "minecraft:bread";
        F.a[298] = "minecraft:leather_helmet";
        F.a[299] = "minecraft:leather_chestplate";
        F.a[300] = "minecraft:leather_leggings";
        F.a[301] = "minecraft:leather_boots";
        F.a[302] = "minecraft:chainmail_helmet";
        F.a[303] = "minecraft:chainmail_chestplate";
        F.a[304] = "minecraft:chainmail_leggings";
        F.a[305] = "minecraft:chainmail_boots";
        F.a[306] = "minecraft:iron_helmet";
        F.a[307] = "minecraft:iron_chestplate";
        F.a[308] = "minecraft:iron_leggings";
        F.a[309] = "minecraft:iron_boots";
        F.a[310] = "minecraft:diamond_helmet";
        F.a[311] = "minecraft:diamond_chestplate";
        F.a[312] = "minecraft:diamond_leggings";
        F.a[313] = "minecraft:diamond_boots";
        F.a[314] = "minecraft:golden_helmet";
        F.a[315] = "minecraft:golden_chestplate";
        F.a[316] = "minecraft:golden_leggings";
        F.a[317] = "minecraft:golden_boots";
        F.a[318] = "minecraft:flint";
        F.a[319] = "minecraft:porkchop";
        F.a[320] = "minecraft:cooked_porkchop";
        F.a[321] = "minecraft:painting";
        F.a[322] = "minecraft:golden_apple";
        F.a[323] = "minecraft:sign";
        F.a[324] = "minecraft:wooden_door";
        F.a[325] = "minecraft:bucket";
        F.a[326] = "minecraft:water_bucket";
        F.a[327] = "minecraft:lava_bucket";
        F.a[328] = "minecraft:minecart";
        F.a[329] = "minecraft:saddle";
        F.a[330] = "minecraft:iron_door";
        F.a[331] = "minecraft:redstone";
        F.a[332] = "minecraft:snowball";
        F.a[333] = "minecraft:boat";
        F.a[334] = "minecraft:leather";
        F.a[335] = "minecraft:milk_bucket";
        F.a[336] = "minecraft:brick";
        F.a[337] = "minecraft:clay_ball";
        F.a[338] = "minecraft:reeds";
        F.a[339] = "minecraft:paper";
        F.a[340] = "minecraft:book";
        F.a[341] = "minecraft:slime_ball";
        F.a[342] = "minecraft:chest_minecart";
        F.a[343] = "minecraft:furnace_minecart";
        F.a[344] = "minecraft:egg";
        F.a[345] = "minecraft:compass";
        F.a[346] = "minecraft:fishing_rod";
        F.a[347] = "minecraft:clock";
        F.a[348] = "minecraft:glowstone_dust";
        F.a[349] = "minecraft:fish";
        F.a[350] = "minecraft:cooked_fished";
        F.a[351] = "minecraft:dye";
        F.a[352] = "minecraft:bone";
        F.a[353] = "minecraft:sugar";
        F.a[354] = "minecraft:cake";
        F.a[355] = "minecraft:bed";
        F.a[356] = "minecraft:repeater";
        F.a[357] = "minecraft:cookie";
        F.a[358] = "minecraft:filled_map";
        F.a[359] = "minecraft:shears";
        F.a[360] = "minecraft:melon";
        F.a[361] = "minecraft:pumpkin_seeds";
        F.a[362] = "minecraft:melon_seeds";
        F.a[363] = "minecraft:beef";
        F.a[364] = "minecraft:cooked_beef";
        F.a[365] = "minecraft:chicken";
        F.a[366] = "minecraft:cooked_chicken";
        F.a[367] = "minecraft:rotten_flesh";
        F.a[368] = "minecraft:ender_pearl";
        F.a[369] = "minecraft:blaze_rod";
        F.a[370] = "minecraft:ghast_tear";
        F.a[371] = "minecraft:gold_nugget";
        F.a[372] = "minecraft:nether_wart";
        F.a[373] = "minecraft:potion";
        F.a[374] = "minecraft:glass_bottle";
        F.a[375] = "minecraft:spider_eye";
        F.a[376] = "minecraft:fermented_spider_eye";
        F.a[377] = "minecraft:blaze_powder";
        F.a[378] = "minecraft:magma_cream";
        F.a[379] = "minecraft:brewing_stand";
        F.a[380] = "minecraft:cauldron";
        F.a[381] = "minecraft:ender_eye";
        F.a[382] = "minecraft:speckled_melon";
        F.a[383] = "minecraft:spawn_egg";
        F.a[384] = "minecraft:experience_bottle";
        F.a[385] = "minecraft:fire_charge";
        F.a[386] = "minecraft:writable_book";
        F.a[387] = "minecraft:written_book";
        F.a[388] = "minecraft:emerald";
        F.a[389] = "minecraft:item_frame";
        F.a[390] = "minecraft:flower_pot";
        F.a[391] = "minecraft:carrot";
        F.a[392] = "minecraft:potato";
        F.a[393] = "minecraft:baked_potato";
        F.a[394] = "minecraft:poisonous_potato";
        F.a[395] = "minecraft:map";
        F.a[396] = "minecraft:golden_carrot";
        F.a[397] = "minecraft:skull";
        F.a[398] = "minecraft:carrot_on_a_stick";
        F.a[399] = "minecraft:nether_star";
        F.a[400] = "minecraft:pumpkin_pie";
        F.a[401] = "minecraft:fireworks";
        F.a[402] = "minecraft:firework_charge";
        F.a[403] = "minecraft:enchanted_book";
        F.a[404] = "minecraft:comparator";
        F.a[405] = "minecraft:netherbrick";
        F.a[406] = "minecraft:quartz";
        F.a[407] = "minecraft:tnt_minecart";
        F.a[408] = "minecraft:hopper_minecart";
        F.a[417] = "minecraft:iron_horse_armor";
        F.a[418] = "minecraft:golden_horse_armor";
        F.a[419] = "minecraft:diamond_horse_armor";
        F.a[420] = "minecraft:lead";
        F.a[421] = "minecraft:name_tag";
        F.a[422] = "minecraft:command_block_minecart";
        F.a[2256] = "minecraft:record_13";
        F.a[2257] = "minecraft:record_cat";
        F.a[2258] = "minecraft:record_blocks";
        F.a[2259] = "minecraft:record_chirp";
        F.a[2260] = "minecraft:record_far";
        F.a[2261] = "minecraft:record_mall";
        F.a[2262] = "minecraft:record_mellohi";
        F.a[2263] = "minecraft:record_stal";
        F.a[2264] = "minecraft:record_strad";
        F.a[2265] = "minecraft:record_ward";
        F.a[2266] = "minecraft:record_11";
        F.a[2267] = "minecraft:record_wait";
    }

    @Override
    public r a(r r2) {
        r r3;
        block4: {
            block5: {
                String string = m.b();
                r3 = r2;
                if (string != null) break block4;
                if (!r3.a("id", 99)) break block5;
                r3 = r2;
                if (string != null) break block4;
                short s2 = r3.q("id");
                if (s2 > 0 && s2 < a.length && a[s2] != null) {
                    r2.a("id", a[s2]);
                }
            }
            r3 = r2;
        }
        return r3;
    }
}

