/*
 * Decompiled with CFR 0.150.
 * 
 * Could not load the following classes:
 *  org.lwjgl.opengl.ARBShaderObjects
 */
import org.lwjgl.opengl.ARBShaderObjects;

public class gz {
    public /* synthetic */ int l;
    public /* synthetic */ int ad;
    public /* synthetic */ int al;
    public /* synthetic */ int s;
    public /* synthetic */ int D;
    public /* synthetic */ int ak;
    public /* synthetic */ int j;
    public /* synthetic */ int aw;
    public /* synthetic */ int a;
    public /* synthetic */ int e;
    public /* synthetic */ int an;
    public /* synthetic */ int ag;
    public /* synthetic */ int aj;
    public /* synthetic */ int f;
    public /* synthetic */ int ao;
    public /* synthetic */ int O;
    public /* synthetic */ int C;
    public /* synthetic */ int T;
    public /* synthetic */ int i;
    public /* synthetic */ int ar;
    public /* synthetic */ int V;
    public /* synthetic */ int N;
    public /* synthetic */ int af;
    public /* synthetic */ int U;
    public /* synthetic */ int M;
    public /* synthetic */ int w;
    public /* synthetic */ int p;
    public /* synthetic */ int h;
    public /* synthetic */ int H;
    public /* synthetic */ int I;
    public /* synthetic */ int E;
    public /* synthetic */ int x;
    public /* synthetic */ int ae;
    public /* synthetic */ int S;
    public /* synthetic */ int t;
    public /* synthetic */ int v;
    public /* synthetic */ int ai;
    public /* synthetic */ int y;
    public /* synthetic */ int K;
    public /* synthetic */ int ap;
    public /* synthetic */ int d;
    public /* synthetic */ int P;
    public /* synthetic */ int Y;
    public /* synthetic */ int R;
    public /* synthetic */ int L;
    public /* synthetic */ int o;
    public /* synthetic */ int as;
    public /* synthetic */ int av;
    public /* synthetic */ int z;
    public /* synthetic */ int G;
    public /* synthetic */ int am;
    public /* synthetic */ int X;
    public /* synthetic */ int aq;
    public /* synthetic */ int r;
    public /* synthetic */ int J;
    public /* synthetic */ int F;
    public /* synthetic */ int ab;
    public /* synthetic */ int at;
    public /* synthetic */ int aa;
    public /* synthetic */ int b;
    public /* synthetic */ int c;
    public /* synthetic */ int q;
    public /* synthetic */ int Q;
    public /* synthetic */ int k;
    public /* synthetic */ int B;
    public /* synthetic */ int A;
    public /* synthetic */ int Z;
    public /* synthetic */ int ah;
    public /* synthetic */ int g;
    public /* synthetic */ int m;
    public /* synthetic */ int ac;
    public /* synthetic */ int n;
    public /* synthetic */ int u;
    public /* synthetic */ int au;
    public /* synthetic */ int W;

    public gz(int n2) {
        this.E = n2;
        this.S = ARBShaderObjects.glGetUniformLocationARB((int)n2, (CharSequence)"texture");
        this.C = ARBShaderObjects.glGetUniformLocationARB((int)n2, (CharSequence)"lightmap");
        this.R = ARBShaderObjects.glGetUniformLocationARB((int)n2, (CharSequence)"normals");
        this.n = ARBShaderObjects.glGetUniformLocationARB((int)n2, (CharSequence)"specular");
        this.M = ARBShaderObjects.glGetUniformLocationARB((int)n2, (CharSequence)"shadow");
        this.ag = ARBShaderObjects.glGetUniformLocationARB((int)n2, (CharSequence)"watershadow");
        this.ar = ARBShaderObjects.glGetUniformLocationARB((int)n2, (CharSequence)"shadowtex0");
        this.s = ARBShaderObjects.glGetUniformLocationARB((int)n2, (CharSequence)"shadowtex1");
        this.P = ARBShaderObjects.glGetUniformLocationARB((int)n2, (CharSequence)"depthtex0");
        this.at = ARBShaderObjects.glGetUniformLocationARB((int)n2, (CharSequence)"depthtex1");
        this.X = ARBShaderObjects.glGetUniformLocationARB((int)n2, (CharSequence)"shadowcolor");
        this.a = ARBShaderObjects.glGetUniformLocationARB((int)n2, (CharSequence)"shadowcolor0");
        this.d = ARBShaderObjects.glGetUniformLocationARB((int)n2, (CharSequence)"shadowcolor1");
        this.ad = ARBShaderObjects.glGetUniformLocationARB((int)n2, (CharSequence)"noisetex");
        this.am = ARBShaderObjects.glGetUniformLocationARB((int)n2, (CharSequence)"gcolor");
        this.aq = ARBShaderObjects.glGetUniformLocationARB((int)n2, (CharSequence)"gdepth");
        this.Y = ARBShaderObjects.glGetUniformLocationARB((int)n2, (CharSequence)"gnormal");
        this.e = ARBShaderObjects.glGetUniformLocationARB((int)n2, (CharSequence)"composite");
        this.ap = ARBShaderObjects.glGetUniformLocationARB((int)n2, (CharSequence)"gaux1");
        this.ah = ARBShaderObjects.glGetUniformLocationARB((int)n2, (CharSequence)"gaux2");
        this.L = ARBShaderObjects.glGetUniformLocationARB((int)n2, (CharSequence)"gaux3");
        this.x = ARBShaderObjects.glGetUniformLocationARB((int)n2, (CharSequence)"gaux4");
        this.r = ARBShaderObjects.glGetUniformLocationARB((int)n2, (CharSequence)"colortex0");
        this.al = ARBShaderObjects.glGetUniformLocationARB((int)n2, (CharSequence)"colortex1");
        this.i = ARBShaderObjects.glGetUniformLocationARB((int)n2, (CharSequence)"colortex2");
        this.h = ARBShaderObjects.glGetUniformLocationARB((int)n2, (CharSequence)"colortex3");
        this.aw = ARBShaderObjects.glGetUniformLocationARB((int)n2, (CharSequence)"colortex4");
        this.T = ARBShaderObjects.glGetUniformLocationARB((int)n2, (CharSequence)"colortex5");
        this.F = ARBShaderObjects.glGetUniformLocationARB((int)n2, (CharSequence)"colortex6");
        this.c = ARBShaderObjects.glGetUniformLocationARB((int)n2, (CharSequence)"colortex7");
        this.Z = ARBShaderObjects.glGetUniformLocationARB((int)n2, (CharSequence)"gdepthtex");
        this.A = ARBShaderObjects.glGetUniformLocationARB((int)n2, (CharSequence)"depthtex2");
        this.O = ARBShaderObjects.glGetUniformLocationARB((int)n2, (CharSequence)"tex");
        this.B = ARBShaderObjects.glGetUniformLocationARB((int)n2, (CharSequence)"heldItemId");
        this.p = ARBShaderObjects.glGetUniformLocationARB((int)n2, (CharSequence)"heldBlockLightValue");
        this.j = ARBShaderObjects.glGetUniformLocationARB((int)n2, (CharSequence)"fogMode");
        this.D = ARBShaderObjects.glGetUniformLocationARB((int)n2, (CharSequence)"fogColor");
        this.an = ARBShaderObjects.glGetUniformLocationARB((int)n2, (CharSequence)"skyColor");
        this.m = ARBShaderObjects.glGetUniformLocationARB((int)n2, (CharSequence)"worldTime");
        this.I = ARBShaderObjects.glGetUniformLocationARB((int)n2, (CharSequence)"moonPhase");
        this.H = ARBShaderObjects.glGetUniformLocationARB((int)n2, (CharSequence)"frameTimeCounter");
        this.ae = ARBShaderObjects.glGetUniformLocationARB((int)n2, (CharSequence)"sunAngle");
        this.K = ARBShaderObjects.glGetUniformLocationARB((int)n2, (CharSequence)"shadowAngle");
        this.V = ARBShaderObjects.glGetUniformLocationARB((int)n2, (CharSequence)"rainStrength");
        this.as = ARBShaderObjects.glGetUniformLocationARB((int)n2, (CharSequence)"aspectRatio");
        this.aa = ARBShaderObjects.glGetUniformLocationARB((int)n2, (CharSequence)"viewWidth");
        this.q = ARBShaderObjects.glGetUniformLocationARB((int)n2, (CharSequence)"viewHeight");
        this.ak = ARBShaderObjects.glGetUniformLocationARB((int)n2, (CharSequence)"near");
        this.ab = ARBShaderObjects.glGetUniformLocationARB((int)n2, (CharSequence)"far");
        this.ai = ARBShaderObjects.glGetUniformLocationARB((int)n2, (CharSequence)"sunPosition");
        this.u = ARBShaderObjects.glGetUniformLocationARB((int)n2, (CharSequence)"moonPosition");
        this.f = ARBShaderObjects.glGetUniformLocationARB((int)n2, (CharSequence)"upPosition");
        this.y = ARBShaderObjects.glGetUniformLocationARB((int)n2, (CharSequence)"previousCameraPosition");
        this.J = ARBShaderObjects.glGetUniformLocationARB((int)n2, (CharSequence)"cameraPosition");
        this.af = ARBShaderObjects.glGetUniformLocationARB((int)n2, (CharSequence)"gbufferModelView");
        this.Q = ARBShaderObjects.glGetUniformLocationARB((int)n2, (CharSequence)"gbufferModelViewInverse");
        this.ac = ARBShaderObjects.glGetUniformLocationARB((int)n2, (CharSequence)"gbufferPreviousProjection");
        this.g = ARBShaderObjects.glGetUniformLocationARB((int)n2, (CharSequence)"gbufferProjection");
        this.t = ARBShaderObjects.glGetUniformLocationARB((int)n2, (CharSequence)"gbufferProjectionInverse");
        this.w = ARBShaderObjects.glGetUniformLocationARB((int)n2, (CharSequence)"gbufferPreviousModelView");
        this.ao = ARBShaderObjects.glGetUniformLocationARB((int)n2, (CharSequence)"shadowProjection");
        this.z = ARBShaderObjects.glGetUniformLocationARB((int)n2, (CharSequence)"shadowProjectionInverse");
        this.k = ARBShaderObjects.glGetUniformLocationARB((int)n2, (CharSequence)"shadowModelView");
        this.W = ARBShaderObjects.glGetUniformLocationARB((int)n2, (CharSequence)"shadowModelViewInverse");
        this.N = ARBShaderObjects.glGetUniformLocationARB((int)n2, (CharSequence)"wetness");
        this.o = ARBShaderObjects.glGetUniformLocationARB((int)n2, (CharSequence)"eyeAltitude");
        this.v = ARBShaderObjects.glGetUniformLocationARB((int)n2, (CharSequence)"eyeBrightness");
        this.l = ARBShaderObjects.glGetUniformLocationARB((int)n2, (CharSequence)"eyeBrightnessSmooth");
        this.U = ARBShaderObjects.glGetUniformLocationARB((int)n2, (CharSequence)"terrainTextureSize");
        this.aj = ARBShaderObjects.glGetUniformLocationARB((int)n2, (CharSequence)"terrainIconSize");
        this.G = ARBShaderObjects.glGetUniformLocationARB((int)n2, (CharSequence)"isEyeInWater");
        this.au = ARBShaderObjects.glGetUniformLocationARB((int)n2, (CharSequence)"hideGUI");
        this.av = ARBShaderObjects.glGetUniformLocationARB((int)n2, (CharSequence)"centerDepthSmooth");
        this.b = ARBShaderObjects.glGetUniformLocationARB((int)n2, (CharSequence)"atlasSize");
    }
}

