/*
 * Decompiled with CFR 0.150.
 */
package net.minecraft.u;

import net.minecraft.ar.d;
import net.minecraft.ar.v;
import net.minecraft.u.f;

public class E {
    public static final /* synthetic */ d fe;
    public static final /* synthetic */ d h;
    public static final /* synthetic */ d gk;
    public static final /* synthetic */ d gQ;
    public static final /* synthetic */ d b8;
    public static final /* synthetic */ d gG;
    public static final /* synthetic */ d d9;
    public static final /* synthetic */ d cJ;
    public static final /* synthetic */ d e_;
    public static final /* synthetic */ d gO;
    public static final /* synthetic */ d aN;
    public static final /* synthetic */ d g8;
    public static final /* synthetic */ d gH;
    public static final /* synthetic */ d cj;
    public static final /* synthetic */ d e4;
    public static final /* synthetic */ d hQ;
    public static final /* synthetic */ d r;
    public static final /* synthetic */ d h4;
    public static final /* synthetic */ d by;
    public static final /* synthetic */ d go;
    public static final /* synthetic */ d fu;
    public static final /* synthetic */ d gX;
    public static final /* synthetic */ d a9;
    public static final /* synthetic */ d dO;
    public static final /* synthetic */ d eU;
    public static final /* synthetic */ d d6;
    public static final /* synthetic */ d dh;
    public static final /* synthetic */ d I;
    public static final /* synthetic */ d f3;
    public static final /* synthetic */ d cb;
    public static final /* synthetic */ d c4;
    public static final /* synthetic */ d eO;
    public static final /* synthetic */ d fJ;
    public static final /* synthetic */ d aj;
    public static final /* synthetic */ d bJ;
    public static final /* synthetic */ d U;
    public static final /* synthetic */ d fO;
    public static final /* synthetic */ d cH;
    public static final /* synthetic */ d bK;
    public static final /* synthetic */ d au;
    public static final /* synthetic */ d aL;
    public static final /* synthetic */ d f8;
    public static final /* synthetic */ d fy;
    public static final /* synthetic */ d hS;
    public static final /* synthetic */ d cQ;
    public static final /* synthetic */ d dW;
    public static final /* synthetic */ d hE;
    public static final /* synthetic */ d bM;
    public static final /* synthetic */ d c7;
    public static final /* synthetic */ d bw;
    public static final /* synthetic */ d h2;
    public static final /* synthetic */ d fw;
    public static final /* synthetic */ d dS;
    public static final /* synthetic */ d cR;
    public static final /* synthetic */ d aw;
    public static final /* synthetic */ d cn;
    public static final /* synthetic */ d l;
    public static final /* synthetic */ d hF;
    public static final /* synthetic */ d gV;
    public static final /* synthetic */ d bi;
    public static final /* synthetic */ d aV;
    public static final /* synthetic */ d g1;
    public static final /* synthetic */ d gA;
    public static final /* synthetic */ d eT;
    public static final /* synthetic */ d eQ;
    public static final /* synthetic */ d dz;
    public static final /* synthetic */ d et;
    public static final /* synthetic */ d bG;
    public static final /* synthetic */ d gz;
    public static final /* synthetic */ d d2;
    public static final /* synthetic */ d gD;
    public static final /* synthetic */ d aU;
    public static final /* synthetic */ d cN;
    public static final /* synthetic */ d cc;
    public static final /* synthetic */ d bo;
    public static final /* synthetic */ d hO;
    public static final /* synthetic */ d f;
    public static final /* synthetic */ d cm;
    public static final /* synthetic */ d cA;
    public static final /* synthetic */ d D;
    public static final /* synthetic */ d bf;
    public static final /* synthetic */ d gw;
    public static final /* synthetic */ d aY;
    public static final /* synthetic */ d gB;
    public static final /* synthetic */ d d8;
    public static final /* synthetic */ d bu;
    public static final /* synthetic */ d b4;
    public static final /* synthetic */ d cy;
    public static final /* synthetic */ d cV;
    public static final /* synthetic */ d eZ;
    public static final /* synthetic */ d a2;
    public static final /* synthetic */ d hv;
    public static final /* synthetic */ d ac;
    public static final /* synthetic */ d d_;
    public static final /* synthetic */ d eB;
    public static final /* synthetic */ d h0;
    public static final /* synthetic */ d bk;
    public static final /* synthetic */ d hJ;
    public static final /* synthetic */ d fF;
    public static final /* synthetic */ d gI;
    public static final /* synthetic */ d i;
    public static final /* synthetic */ d fB;
    public static final /* synthetic */ d e9;
    public static final /* synthetic */ d al;
    public static final /* synthetic */ d f5;
    public static final /* synthetic */ d u;
    public static final /* synthetic */ d bv;
    public static final /* synthetic */ d dn;
    public static final /* synthetic */ d aD;
    public static final /* synthetic */ d ay;
    public static final /* synthetic */ d s;
    public static final /* synthetic */ d gl;
    public static final /* synthetic */ d a0;
    public static final /* synthetic */ d ag;
    public static final /* synthetic */ d hk;
    public static final /* synthetic */ d dt;
    public static final /* synthetic */ d g5;
    public static final /* synthetic */ d C;
    public static final /* synthetic */ d gg;
    public static final /* synthetic */ d f2;
    public static final /* synthetic */ d c_;
    public static final /* synthetic */ d dj;
    public static final /* synthetic */ d e3;
    public static final /* synthetic */ d cY;
    public static final /* synthetic */ d b5;
    public static final /* synthetic */ d hT;
    public static final /* synthetic */ d ff;
    public static final /* synthetic */ d g9;
    public static final /* synthetic */ d bP;
    public static final /* synthetic */ d hU;
    public static final /* synthetic */ d hi;
    public static final /* synthetic */ d hP;
    public static final /* synthetic */ d ec;
    public static final /* synthetic */ d ck;
    public static final /* synthetic */ d m;
    public static final /* synthetic */ d fR;
    public static final /* synthetic */ d cX;
    public static final /* synthetic */ d c1;
    public static final /* synthetic */ d ey;
    public static final /* synthetic */ d bs;
    public static final /* synthetic */ d ct;
    public static final /* synthetic */ d ap;
    public static final /* synthetic */ d d4;
    public static final /* synthetic */ d dp;
    public static final /* synthetic */ d cZ;
    public static final /* synthetic */ d a6;
    public static final /* synthetic */ d dx;
    public static final /* synthetic */ d bN;
    public static final /* synthetic */ d em;
    public static final /* synthetic */ d ee;
    public static final /* synthetic */ d gJ;
    public static final /* synthetic */ d fU;
    public static final /* synthetic */ d h3;
    public static final /* synthetic */ d dl;
    public static final /* synthetic */ d d7;
    public static final /* synthetic */ d gx;
    public static final /* synthetic */ d bE;
    public static final /* synthetic */ d bB;
    public static final /* synthetic */ d aJ;
    public static final /* synthetic */ d fC;
    public static final /* synthetic */ d eD;
    public static final /* synthetic */ d aK;
    public static final /* synthetic */ d cW;
    public static final /* synthetic */ d e7;
    public static final /* synthetic */ d fn;
    public static final /* synthetic */ d k;
    public static final /* synthetic */ d ew;
    public static final /* synthetic */ d H;
    public static final /* synthetic */ d ah;
    public static final /* synthetic */ d ch;
    public static final /* synthetic */ d ci;
    public static final /* synthetic */ d eq;
    public static final /* synthetic */ d fQ;
    public static final /* synthetic */ d ho;
    public static final /* synthetic */ d bS;
    public static final /* synthetic */ d hf;
    public static final /* synthetic */ d hy;
    public static final /* synthetic */ d hw;
    public static final /* synthetic */ d fV;
    public static final /* synthetic */ d bU;
    public static final /* synthetic */ d o;
    public static final /* synthetic */ d fs;
    public static final /* synthetic */ d ce;
    public static final /* synthetic */ d ei;
    public static final /* synthetic */ d dQ;
    public static final /* synthetic */ d d3;
    public static final /* synthetic */ d cs;
    public static final /* synthetic */ d ex;
    public static final /* synthetic */ d g0;
    public static final /* synthetic */ d c0;
    public static final /* synthetic */ d dq;
    public static final /* synthetic */ d cg;
    public static final /* synthetic */ d en;
    public static final /* synthetic */ d fc;
    public static final /* synthetic */ d hH;
    public static final /* synthetic */ d a8;
    public static final /* synthetic */ d eX;
    public static final /* synthetic */ d K;
    public static final /* synthetic */ d gK;
    public static final /* synthetic */ d cK;
    public static final /* synthetic */ d gj;
    public static final /* synthetic */ d gs;
    public static final /* synthetic */ d bq;
    public static final /* synthetic */ d fX;
    public static final /* synthetic */ d bn;
    public static final /* synthetic */ d ev;
    public static final /* synthetic */ d bl;
    public static final /* synthetic */ d b3;
    public static final /* synthetic */ d as;
    public static final /* synthetic */ d aO;
    public static final /* synthetic */ d hr;
    public static final /* synthetic */ d bQ;
    public static final /* synthetic */ d eI;
    public static final /* synthetic */ d aS;
    public static final /* synthetic */ d da;
    public static final /* synthetic */ d f7;
    public static final /* synthetic */ d dC;
    public static final /* synthetic */ d gW;
    public static final /* synthetic */ d fl;
    public static final /* synthetic */ d cS;
    public static final /* synthetic */ d cD;
    public static final /* synthetic */ d b6;
    public static final /* synthetic */ d c9;
    public static final /* synthetic */ d gC;
    public static final /* synthetic */ d cE;
    public static final /* synthetic */ d d;
    public static final /* synthetic */ d an;
    public static final /* synthetic */ d eA;
    public static final /* synthetic */ d gZ;
    public static final /* synthetic */ d bc;
    public static final /* synthetic */ d hd;
    public static final /* synthetic */ d aX;
    public static final /* synthetic */ d dV;
    public static final /* synthetic */ d gR;
    public static final /* synthetic */ d fz;
    public static final /* synthetic */ d X;
    public static final /* synthetic */ d aQ;
    public static final /* synthetic */ d hb;
    public static final /* synthetic */ d g2;
    public static final /* synthetic */ d eE;
    public static final /* synthetic */ d hY;
    public static final /* synthetic */ d w;
    public static final /* synthetic */ d cC;
    public static final /* synthetic */ d ea;
    public static final /* synthetic */ d a1;
    public static final /* synthetic */ d S;
    public static final /* synthetic */ d fE;
    public static final /* synthetic */ d dJ;
    public static final /* synthetic */ d aq;
    public static final /* synthetic */ d a7;
    public static final /* synthetic */ d f9;
    public static final /* synthetic */ d dc;
    public static final /* synthetic */ d ed;
    public static final /* synthetic */ d hN;
    public static final /* synthetic */ d fj;
    public static final /* synthetic */ d hs;
    public static final /* synthetic */ d dG;
    public static final /* synthetic */ d aH;
    public static final /* synthetic */ d aE;
    public static final /* synthetic */ d bp;
    public static final /* synthetic */ d z;
    public static final /* synthetic */ d co;
    public static final /* synthetic */ d ax;
    public static final /* synthetic */ d f_;
    public static final /* synthetic */ d dy;
    public static final /* synthetic */ d bV;
    public static final /* synthetic */ d g3;
    public static final /* synthetic */ d fv;
    public static final /* synthetic */ d hW;
    public static final /* synthetic */ d fm;
    public static final /* synthetic */ d fN;
    public static final /* synthetic */ d v;
    public static final /* synthetic */ d dM;
    public static final /* synthetic */ d eW;
    public static final /* synthetic */ d dK;
    public static final /* synthetic */ d gT;
    public static final /* synthetic */ d b_;
    public static final /* synthetic */ d eP;
    public static final /* synthetic */ d b9;
    public static final /* synthetic */ d fb;
    public static final /* synthetic */ d fI;
    public static final /* synthetic */ d hI;
    public static final /* synthetic */ d eK;
    public static final /* synthetic */ d di;
    public static final /* synthetic */ d fk;
    public static final /* synthetic */ d fp;
    public static final /* synthetic */ d eC;
    public static final /* synthetic */ d e8;
    public static final /* synthetic */ d n;
    public static final /* synthetic */ d e0;
    public static final /* synthetic */ d dZ;
    public static final /* synthetic */ d aF;
    public static final /* synthetic */ d ak;
    public static final /* synthetic */ d er;
    public static final /* synthetic */ d aG;
    public static final /* synthetic */ d eL;
    public static final /* synthetic */ d G;
    public static final /* synthetic */ d B;
    public static final /* synthetic */ d ar;
    public static final /* synthetic */ d he;
    public static final /* synthetic */ d g_;
    public static final /* synthetic */ d hM;
    public static final /* synthetic */ d gN;
    public static final /* synthetic */ d dP;
    public static final /* synthetic */ d dg;
    public static final /* synthetic */ d db;
    public static final /* synthetic */ d e;
    public static final /* synthetic */ d d0;
    public static final /* synthetic */ d bg;
    public static final /* synthetic */ d cf;
    public static final /* synthetic */ d fd;
    public static final /* synthetic */ d bz;
    public static final /* synthetic */ d hV;
    public static final /* synthetic */ d fY;
    public static final /* synthetic */ d aa;
    public static final /* synthetic */ d a_;
    public static final /* synthetic */ d a5;
    public static final /* synthetic */ d ab;
    public static final /* synthetic */ d O;
    public static final /* synthetic */ d a;
    public static final /* synthetic */ d hD;
    public static final /* synthetic */ d bj;
    public static final /* synthetic */ d b1;
    public static final /* synthetic */ d de;
    public static final /* synthetic */ d ef;
    public static final /* synthetic */ d fr;
    public static final /* synthetic */ d cL;
    public static final /* synthetic */ d a4;
    public static final /* synthetic */ d hm;
    public static final /* synthetic */ d dT;
    public static final /* synthetic */ d hu;
    public static final /* synthetic */ d dU;
    public static final /* synthetic */ d ek;
    public static final /* synthetic */ d cU;
    public static final /* synthetic */ d ht;
    public static final /* synthetic */ d fM;
    public static final /* synthetic */ d du;
    public static final /* synthetic */ d ep;
    public static final /* synthetic */ d g6;
    public static final /* synthetic */ d ad;
    public static final /* synthetic */ d hh;
    public static final /* synthetic */ d dI;
    public static final /* synthetic */ d fT;
    public static final /* synthetic */ d gp;
    public static final /* synthetic */ d Y;
    public static final /* synthetic */ d bX;
    public static final /* synthetic */ d hc;
    public static final /* synthetic */ d aB;
    public static final /* synthetic */ d bF;
    public static final /* synthetic */ d gY;
    public static final /* synthetic */ d dF;
    public static final /* synthetic */ d b2;
    public static final /* synthetic */ d e2;
    public static final /* synthetic */ d fa;
    public static final /* synthetic */ d hg;
    public static final /* synthetic */ d b7;
    public static final /* synthetic */ d c8;
    public static final /* synthetic */ d fW;
    public static final /* synthetic */ d dH;
    public static final /* synthetic */ d f0;
    public static final /* synthetic */ d eG;
    public static final /* synthetic */ d eH;
    public static final /* synthetic */ d R;
    public static final /* synthetic */ d eS;
    public static final /* synthetic */ d aM;
    public static final /* synthetic */ d dB;
    public static final /* synthetic */ d W;
    public static final /* synthetic */ d fo;
    public static final /* synthetic */ d dA;
    public static final /* synthetic */ d cv;
    public static final /* synthetic */ d bY;
    public static final /* synthetic */ d eY;
    public static final /* synthetic */ d fi;
    public static final /* synthetic */ d ds;
    public static final /* synthetic */ d b;
    public static final /* synthetic */ d gS;
    public static final /* synthetic */ d aT;
    public static final /* synthetic */ d gq;
    public static final /* synthetic */ d ga;
    public static final /* synthetic */ d bm;
    public static final /* synthetic */ d hC;
    public static final /* synthetic */ d cM;
    public static final /* synthetic */ d ej;
    public static final /* synthetic */ d hX;
    public static final /* synthetic */ d L;
    public static final /* synthetic */ d e6;
    public static final /* synthetic */ d ez;
    public static final /* synthetic */ d dD;
    public static final /* synthetic */ d c;
    public static final /* synthetic */ d hL;
    public static final /* synthetic */ d e1;
    public static final /* synthetic */ d y;
    public static final /* synthetic */ d t;
    public static final /* synthetic */ d V;
    public static final /* synthetic */ d q;
    public static final /* synthetic */ d gr;
    public static final /* synthetic */ d bt;
    public static final /* synthetic */ d dm;
    public static final /* synthetic */ d dE;
    public static final /* synthetic */ d ha;
    public static final /* synthetic */ d el;
    public static final /* synthetic */ d gL;
    public static final /* synthetic */ d be;
    public static final /* synthetic */ d dk;
    public static final /* synthetic */ d ft;
    public static final /* synthetic */ d bR;
    public static final /* synthetic */ d gt;
    public static final /* synthetic */ d av;
    public static final /* synthetic */ d gF;
    public static final /* synthetic */ d hj;
    public static final /* synthetic */ d gf;
    public static final /* synthetic */ d hA;
    public static final /* synthetic */ d M;
    public static final /* synthetic */ d g7;
    public static final /* synthetic */ d hZ;
    public static final /* synthetic */ d br;
    public static final /* synthetic */ d cT;
    public static final /* synthetic */ d aI;
    public static final /* synthetic */ d Z;
    public static final /* synthetic */ d bx;
    public static final /* synthetic */ d bD;
    public static final /* synthetic */ d af;
    public static final /* synthetic */ d gc;
    public static final /* synthetic */ d cx;
    public static final /* synthetic */ d ae;
    public static final /* synthetic */ d hK;
    public static final /* synthetic */ d dR;
    public static final /* synthetic */ d fS;
    public static final /* synthetic */ d eM;
    public static final /* synthetic */ d cw;
    public static final /* synthetic */ d cd;
    public static final /* synthetic */ d bW;
    public static final /* synthetic */ d cp;
    public static final /* synthetic */ d bb;
    public static final /* synthetic */ d bA;
    public static final /* synthetic */ d eg;
    public static final /* synthetic */ d az;
    public static final /* synthetic */ d fh;
    public static final /* synthetic */ d J;
    public static final /* synthetic */ d cl;
    public static final /* synthetic */ d ao;
    public static final /* synthetic */ d eJ;
    public static final /* synthetic */ d gb;
    public static final /* synthetic */ d gP;
    public static final /* synthetic */ d ba;
    public static final /* synthetic */ d c2;
    public static final /* synthetic */ d c5;
    public static final /* synthetic */ d cr;
    public static final /* synthetic */ d gn;
    public static final /* synthetic */ d aP;
    public static final /* synthetic */ d gv;
    public static final /* synthetic */ d bC;
    public static final /* synthetic */ d hq;
    public static final /* synthetic */ d f4;
    public static final /* synthetic */ d N;
    public static final /* synthetic */ d es;
    public static final /* synthetic */ d F;
    public static final /* synthetic */ d cI;
    public static final /* synthetic */ d d5;
    public static final /* synthetic */ d eN;
    public static final /* synthetic */ d aA;
    public static final /* synthetic */ d cF;
    public static final /* synthetic */ d eR;
    public static final /* synthetic */ d aW;
    public static final /* synthetic */ d x;
    public static final /* synthetic */ d bZ;
    public static final /* synthetic */ d bO;
    public static final /* synthetic */ d hn;
    public static final /* synthetic */ d aZ;
    public static final /* synthetic */ d p;
    public static final /* synthetic */ d c6;
    public static final /* synthetic */ d h1;
    public static final /* synthetic */ d fZ;
    public static final /* synthetic */ d cB;
    public static final /* synthetic */ d g;
    public static final /* synthetic */ d hG;
    public static final /* synthetic */ d bH;
    public static final /* synthetic */ d dL;
    public static final /* synthetic */ d fH;
    public static final /* synthetic */ d gy;
    public static final /* synthetic */ d gi;
    public static final /* synthetic */ d a3;
    public static final /* synthetic */ d j;
    public static final /* synthetic */ d aC;
    public static final /* synthetic */ d gh;
    public static final /* synthetic */ d hl;
    public static final /* synthetic */ d hp;
    public static final /* synthetic */ d bd;
    public static final /* synthetic */ d dv;
    public static final /* synthetic */ d fK;
    public static final /* synthetic */ d hB;
    public static final /* synthetic */ d d1;
    public static final /* synthetic */ d bI;
    public static final /* synthetic */ d eb;
    public static final /* synthetic */ d b0;
    public static final /* synthetic */ d gE;
    public static final /* synthetic */ d gm;
    public static final /* synthetic */ d ai;
    public static final /* synthetic */ d dX;
    public static final /* synthetic */ d bL;
    public static final /* synthetic */ d dN;
    public static final /* synthetic */ d cz;
    public static final /* synthetic */ d fL;
    public static final /* synthetic */ d e5;
    public static final /* synthetic */ d am;
    public static final /* synthetic */ d cq;
    public static final /* synthetic */ d dY;
    public static final /* synthetic */ d aR;
    public static final /* synthetic */ d eo;
    public static final /* synthetic */ d ca;
    public static final /* synthetic */ d df;
    public static final /* synthetic */ d gu;
    public static final /* synthetic */ d hz;
    public static final /* synthetic */ d fP;
    public static final /* synthetic */ d hR;
    public static final /* synthetic */ d dr;
    public static final /* synthetic */ d A;
    public static final /* synthetic */ d E;
    public static final /* synthetic */ d bh;
    public static final /* synthetic */ d at;
    public static final /* synthetic */ d eu;
    public static final /* synthetic */ d fD;
    public static final /* synthetic */ d fg;
    public static final /* synthetic */ d eF;
    public static final /* synthetic */ d Q;
    public static final /* synthetic */ d f1;
    public static final /* synthetic */ d cu;
    public static final /* synthetic */ d gM;
    public static final /* synthetic */ d c3;
    public static final /* synthetic */ d ge;
    public static final /* synthetic */ d gU;
    public static final /* synthetic */ d cO;
    public static final /* synthetic */ d g4;
    public static final /* synthetic */ d bT;
    public static final /* synthetic */ d fx;
    public static final /* synthetic */ d gd;
    public static final /* synthetic */ d dw;
    public static final /* synthetic */ d fA;
    public static final /* synthetic */ d cG;
    public static final /* synthetic */ d hx;
    public static final /* synthetic */ d fq;
    public static final /* synthetic */ d eV;
    public static final /* synthetic */ d fG;
    public static final /* synthetic */ d dd;
    public static final /* synthetic */ d eh;
    public static final /* synthetic */ d P;
    public static final /* synthetic */ d cP;
    public static final /* synthetic */ d f6;
    public static final /* synthetic */ d T;

    private static IllegalStateException a(IllegalStateException illegalStateException) {
        return illegalStateException;
    }

    static {
        if (!net.minecraft.u.f.b()) {
            throw new RuntimeException("Accessed Sounds before Bootstrap!");
        }
        gD = net.minecraft.u.E.a("ambient.cave");
        fD = net.minecraft.u.E.a("block.anvil.break");
        bc = net.minecraft.u.E.a("block.anvil.destroy");
        Z = net.minecraft.u.E.a("block.anvil.fall");
        dL = net.minecraft.u.E.a("block.anvil.hit");
        aM = net.minecraft.u.E.a("block.anvil.land");
        ex = net.minecraft.u.E.a("block.anvil.place");
        c8 = net.minecraft.u.E.a("block.anvil.step");
        a0 = net.minecraft.u.E.a("block.anvil.use");
        aN = net.minecraft.u.E.a("entity.armorstand.break");
        dI = net.minecraft.u.E.a("entity.armorstand.fall");
        cy = net.minecraft.u.E.a("entity.armorstand.hit");
        cL = net.minecraft.u.E.a("entity.armorstand.place");
        ht = net.minecraft.u.E.a("item.armor.equip_chain");
        cx = net.minecraft.u.E.a("item.armor.equip_diamond");
        g2 = net.minecraft.u.E.a("item.armor.equip_elytra");
        hU = net.minecraft.u.E.a("item.armor.equip_generic");
        hc = net.minecraft.u.E.a("item.armor.equip_gold");
        Q = net.minecraft.u.E.a("item.armor.equip_iron");
        dR = net.minecraft.u.E.a("item.armor.equip_leather");
        e_ = net.minecraft.u.E.a("entity.arrow.hit");
        dZ = net.minecraft.u.E.a("entity.arrow.hit_player");
        hM = net.minecraft.u.E.a("entity.arrow.shoot");
        gF = net.minecraft.u.E.a("entity.bat.ambient");
        cI = net.minecraft.u.E.a("entity.bat.death");
        hx = net.minecraft.u.E.a("entity.bat.hurt");
        aS = net.minecraft.u.E.a("entity.bat.loop");
        gp = net.minecraft.u.E.a("entity.bat.takeoff");
        aH = net.minecraft.u.E.a("entity.blaze.ambient");
        hQ = net.minecraft.u.E.a("entity.blaze.burn");
        gk = net.minecraft.u.E.a("entity.blaze.death");
        dF = net.minecraft.u.E.a("entity.blaze.hurt");
        gQ = net.minecraft.u.E.a("entity.blaze.shoot");
        b7 = net.minecraft.u.E.a("entity.boat.paddle_land");
        cb = net.minecraft.u.E.a("entity.boat.paddle_water");
        aX = net.minecraft.u.E.a("entity.bobber.retrieve");
        hL = net.minecraft.u.E.a("entity.bobber.splash");
        bu = net.minecraft.u.E.a("entity.bobber.throw");
        hz = net.minecraft.u.E.a("item.bottle.empty");
        g7 = net.minecraft.u.E.a("item.bottle.fill");
        f3 = net.minecraft.u.E.a("item.bottle.fill_dragonbreath");
        V = net.minecraft.u.E.a("block.brewing_stand.brew");
        cp = net.minecraft.u.E.a("item.bucket.empty");
        dx = net.minecraft.u.E.a("item.bucket.empty_lava");
        gl = net.minecraft.u.E.a("item.bucket.fill");
        eM = net.minecraft.u.E.a("item.bucket.fill_lava");
        d8 = net.minecraft.u.E.a("entity.cat.ambient");
        ew = net.minecraft.u.E.a("entity.cat.death");
        br = net.minecraft.u.E.a("entity.cat.hiss");
        d = net.minecraft.u.E.a("entity.cat.hurt");
        eH = net.minecraft.u.E.a("entity.cat.purr");
        ad = net.minecraft.u.E.a("entity.cat.purreow");
        g0 = net.minecraft.u.E.a("block.chest.close");
        gW = net.minecraft.u.E.a("block.chest.locked");
        b_ = net.minecraft.u.E.a("block.chest.open");
        fl = net.minecraft.u.E.a("entity.chicken.ambient");
        eP = net.minecraft.u.E.a("entity.chicken.death");
        O = net.minecraft.u.E.a("entity.chicken.egg");
        fE = net.minecraft.u.E.a("entity.chicken.hurt");
        H = net.minecraft.u.E.a("entity.chicken.step");
        cH = net.minecraft.u.E.a("block.chorus_flower.death");
        dP = net.minecraft.u.E.a("block.chorus_flower.grow");
        d6 = net.minecraft.u.E.a("item.chorus_fruit.teleport");
        ar = net.minecraft.u.E.a("block.cloth.break");
        hP = net.minecraft.u.E.a("block.cloth.fall");
        c4 = net.minecraft.u.E.a("block.cloth.hit");
        dU = net.minecraft.u.E.a("block.cloth.place");
        bZ = net.minecraft.u.E.a("block.cloth.step");
        bL = net.minecraft.u.E.a("block.comparator.click");
        eE = net.minecraft.u.E.a("entity.cow.ambient");
        n = net.minecraft.u.E.a("entity.cow.death");
        bY = net.minecraft.u.E.a("entity.cow.hurt");
        fw = net.minecraft.u.E.a("entity.cow.milk");
        av = net.minecraft.u.E.a("entity.cow.step");
        bM = net.minecraft.u.E.a("entity.creeper.death");
        cS = net.minecraft.u.E.a("entity.creeper.hurt");
        c_ = net.minecraft.u.E.a("entity.creeper.primed");
        gx = net.minecraft.u.E.a("block.dispenser.dispense");
        dq = net.minecraft.u.E.a("block.dispenser.fail");
        dV = net.minecraft.u.E.a("block.dispenser.launch");
        fJ = net.minecraft.u.E.a("entity.donkey.ambient");
        c1 = net.minecraft.u.E.a("entity.donkey.angry");
        dm = net.minecraft.u.E.a("entity.donkey.chest");
        bW = net.minecraft.u.E.a("entity.donkey.death");
        gZ = net.minecraft.u.E.a("entity.donkey.hurt");
        v = net.minecraft.u.E.a("entity.egg.throw");
        gP = net.minecraft.u.E.a("entity.elder_guardian.ambient");
        ch = net.minecraft.u.E.a("entity.elder_guardian.ambient_land");
        bk = net.minecraft.u.E.a("entity.elder_guardian.curse");
        C = net.minecraft.u.E.a("entity.elder_guardian.death");
        cA = net.minecraft.u.E.a("entity.elder_guardian.death_land");
        fN = net.minecraft.u.E.a("entity.elder_guardian.flop");
        hr = net.minecraft.u.E.a("entity.elder_guardian.hurt");
        dr = net.minecraft.u.E.a("entity.elder_guardian.hurt_land");
        dp = net.minecraft.u.E.a("item.elytra.flying");
        cK = net.minecraft.u.E.a("block.enchantment_table.use");
        cd = net.minecraft.u.E.a("block.enderchest.close");
        cc = net.minecraft.u.E.a("block.enderchest.open");
        e2 = net.minecraft.u.E.a("entity.enderdragon.ambient");
        e1 = net.minecraft.u.E.a("entity.enderdragon.death");
        df = net.minecraft.u.E.a("entity.enderdragon_fireball.explode");
        dB = net.minecraft.u.E.a("entity.enderdragon.flap");
        dA = net.minecraft.u.E.a("entity.enderdragon.growl");
        gT = net.minecraft.u.E.a("entity.enderdragon.hurt");
        b = net.minecraft.u.E.a("entity.enderdragon.shoot");
        f4 = net.minecraft.u.E.a("entity.endereye.death");
        dy = net.minecraft.u.E.a("entity.endereye.launch");
        cF = net.minecraft.u.E.a("entity.endermen.ambient");
        eZ = net.minecraft.u.E.a("entity.endermen.death");
        h0 = net.minecraft.u.E.a("entity.endermen.hurt");
        h1 = net.minecraft.u.E.a("entity.endermen.scream");
        d1 = net.minecraft.u.E.a("entity.endermen.stare");
        ed = net.minecraft.u.E.a("entity.endermen.teleport");
        cX = net.minecraft.u.E.a("entity.endermite.ambient");
        ee = net.minecraft.u.E.a("entity.endermite.death");
        hS = net.minecraft.u.E.a("entity.endermite.hurt");
        bf = net.minecraft.u.E.a("entity.endermite.step");
        bp = net.minecraft.u.E.a("entity.enderpearl.throw");
        dO = net.minecraft.u.E.a("block.end_gateway.spawn");
        c0 = net.minecraft.u.E.a("block.end_portal_frame.fill");
        bH = net.minecraft.u.E.a("block.end_portal.spawn");
        eq = net.minecraft.u.E.a("entity.evocation_fangs.attack");
        gY = net.minecraft.u.E.a("entity.evocation_illager.ambient");
        Y = net.minecraft.u.E.a("entity.evocation_illager.cast_spell");
        a6 = net.minecraft.u.E.a("entity.evocation_illager.death");
        gA = net.minecraft.u.E.a("entity.evocation_illager.hurt");
        d3 = net.minecraft.u.E.a("entity.evocation_illager.prepare_attack");
        fC = net.minecraft.u.E.a("entity.evocation_illager.prepare_summon");
        aK = net.minecraft.u.E.a("entity.evocation_illager.prepare_wololo");
        b6 = net.minecraft.u.E.a("entity.experience_bottle.throw");
        ec = net.minecraft.u.E.a("entity.experience_orb.pickup");
        f5 = net.minecraft.u.E.a("block.fence_gate.close");
        eF = net.minecraft.u.E.a("block.fence_gate.open");
        U = net.minecraft.u.E.a("item.firecharge.use");
        aF = net.minecraft.u.E.a("entity.firework.blast");
        hT = net.minecraft.u.E.a("entity.firework.blast_far");
        d2 = net.minecraft.u.E.a("entity.firework.large_blast");
        ej = net.minecraft.u.E.a("entity.firework.large_blast_far");
        fU = net.minecraft.u.E.a("entity.firework.launch");
        bO = net.minecraft.u.E.a("entity.firework.shoot");
        aZ = net.minecraft.u.E.a("entity.firework.twinkle");
        gO = net.minecraft.u.E.a("entity.firework.twinkle_far");
        ev = net.minecraft.u.E.a("block.fire.ambient");
        gE = net.minecraft.u.E.a("block.fire.extinguish");
        fX = net.minecraft.u.E.a("item.flintandsteel.use");
        cj = net.minecraft.u.E.a("block.furnace.fire_crackle");
        aT = net.minecraft.u.E.a("entity.generic.big_fall");
        b8 = net.minecraft.u.E.a("entity.generic.burn");
        fg = net.minecraft.u.E.a("entity.generic.death");
        en = net.minecraft.u.E.a("entity.generic.drink");
        c5 = net.minecraft.u.E.a("entity.generic.eat");
        bB = net.minecraft.u.E.a("entity.generic.explode");
        dw = net.minecraft.u.E.a("entity.generic.extinguish_fire");
        bw = net.minecraft.u.E.a("entity.generic.hurt");
        b1 = net.minecraft.u.E.a("entity.generic.small_fall");
        er = net.minecraft.u.E.a("entity.generic.splash");
        cT = net.minecraft.u.E.a("entity.generic.swim");
        t = net.minecraft.u.E.a("entity.ghast.ambient");
        R = net.minecraft.u.E.a("entity.ghast.death");
        g9 = net.minecraft.u.E.a("entity.ghast.hurt");
        eS = net.minecraft.u.E.a("entity.ghast.scream");
        fj = net.minecraft.u.E.a("entity.ghast.shoot");
        hC = net.minecraft.u.E.a("entity.ghast.warn");
        ey = net.minecraft.u.E.a("block.glass.break");
        bT = net.minecraft.u.E.a("block.glass.fall");
        aV = net.minecraft.u.E.a("block.glass.hit");
        bQ = net.minecraft.u.E.a("block.glass.place");
        cv = net.minecraft.u.E.a("block.glass.step");
        dH = net.minecraft.u.E.a("block.grass.break");
        eC = net.minecraft.u.E.a("block.grass.fall");
        K = net.minecraft.u.E.a("block.grass.hit");
        gu = net.minecraft.u.E.a("block.grass.place");
        gw = net.minecraft.u.E.a("block.grass.step");
        hG = net.minecraft.u.E.a("block.gravel.break");
        fI = net.minecraft.u.E.a("block.gravel.fall");
        ep = net.minecraft.u.E.a("block.gravel.hit");
        gJ = net.minecraft.u.E.a("block.gravel.place");
        fH = net.minecraft.u.E.a("block.gravel.step");
        dd = net.minecraft.u.E.a("entity.guardian.ambient");
        az = net.minecraft.u.E.a("entity.guardian.ambient_land");
        g5 = net.minecraft.u.E.a("entity.guardian.attack");
        e5 = net.minecraft.u.E.a("entity.guardian.death");
        fP = net.minecraft.u.E.a("entity.guardian.death_land");
        hq = net.minecraft.u.E.a("entity.guardian.flop");
        bJ = net.minecraft.u.E.a("entity.guardian.hurt");
        fy = net.minecraft.u.E.a("entity.guardian.hurt_land");
        gq = net.minecraft.u.E.a("item.hoe.till");
        fZ = net.minecraft.u.E.a("entity.horse.ambient");
        cV = net.minecraft.u.E.a("entity.horse.angry");
        cM = net.minecraft.u.E.a("entity.horse.armor");
        hK = net.minecraft.u.E.a("entity.horse.breathe");
        aU = net.minecraft.u.E.a("entity.horse.death");
        c9 = net.minecraft.u.E.a("entity.horse.eat");
        fk = net.minecraft.u.E.a("entity.horse.gallop");
        f = net.minecraft.u.E.a("entity.horse.hurt");
        cY = net.minecraft.u.E.a("entity.horse.jump");
        bP = net.minecraft.u.E.a("entity.horse.land");
        bd = net.minecraft.u.E.a("entity.horse.saddle");
        bx = net.minecraft.u.E.a("entity.horse.step");
        bq = net.minecraft.u.E.a("entity.horse.step_wood");
        hj = net.minecraft.u.E.a("entity.hostile.big_fall");
        ek = net.minecraft.u.E.a("entity.hostile.death");
        f9 = net.minecraft.u.E.a("entity.hostile.hurt");
        fo = net.minecraft.u.E.a("entity.hostile.small_fall");
        h = net.minecraft.u.E.a("entity.hostile.splash");
        bt = net.minecraft.u.E.a("entity.hostile.swim");
        gf = net.minecraft.u.E.a("entity.husk.ambient");
        a7 = net.minecraft.u.E.a("entity.husk.death");
        cJ = net.minecraft.u.E.a("entity.husk.hurt");
        aa = net.minecraft.u.E.a("entity.husk.step");
        y = net.minecraft.u.E.a("entity.illusion_illager.ambient");
        ck = net.minecraft.u.E.a("entity.illusion_illager.cast_spell");
        g1 = net.minecraft.u.E.a("entity.illusion_illager.death");
        bU = net.minecraft.u.E.a("entity.illusion_illager.hurt");
        gG = net.minecraft.u.E.a("entity.illusion_illager.mirror_move");
        de = net.minecraft.u.E.a("entity.illusion_illager.prepare_blindness");
        bF = net.minecraft.u.E.a("entity.illusion_illager.prepare_mirror");
        bj = net.minecraft.u.E.a("entity.irongolem.attack");
        cq = net.minecraft.u.E.a("entity.irongolem.death");
        gX = net.minecraft.u.E.a("entity.irongolem.hurt");
        z = net.minecraft.u.E.a("entity.irongolem.step");
        S = net.minecraft.u.E.a("block.iron_door.close");
        eR = net.minecraft.u.E.a("block.iron_door.open");
        be = net.minecraft.u.E.a("block.iron_trapdoor.close");
        eN = net.minecraft.u.E.a("block.iron_trapdoor.open");
        a1 = net.minecraft.u.E.a("entity.itemframe.add_item");
        dn = net.minecraft.u.E.a("entity.itemframe.break");
        p = net.minecraft.u.E.a("entity.itemframe.place");
        B = net.minecraft.u.E.a("entity.itemframe.remove_item");
        fd = net.minecraft.u.E.a("entity.itemframe.rotate_item");
        fe = net.minecraft.u.E.a("entity.item.break");
        ak = net.minecraft.u.E.a("entity.item.pickup");
        ez = net.minecraft.u.E.a("block.ladder.break");
        hg = net.minecraft.u.E.a("block.ladder.fall");
        hJ = net.minecraft.u.E.a("block.ladder.hit");
        f1 = net.minecraft.u.E.a("block.ladder.place");
        e = net.minecraft.u.E.a("block.ladder.step");
        gm = net.minecraft.u.E.a("block.lava.ambient");
        as = net.minecraft.u.E.a("block.lava.extinguish");
        ai = net.minecraft.u.E.a("block.lava.pop");
        fS = net.minecraft.u.E.a("entity.leashknot.break");
        dM = net.minecraft.u.E.a("entity.leashknot.place");
        b3 = net.minecraft.u.E.a("block.lever.click");
        go = net.minecraft.u.E.a("entity.lightning.impact");
        hs = net.minecraft.u.E.a("entity.lightning.thunder");
        du = net.minecraft.u.E.a("entity.lingeringpotion.throw");
        cQ = net.minecraft.u.E.a("entity.llama.ambient");
        hi = net.minecraft.u.E.a("entity.llama.angry");
        dv = net.minecraft.u.E.a("entity.llama.chest");
        ef = net.minecraft.u.E.a("entity.llama.death");
        aD = net.minecraft.u.E.a("entity.llama.eat");
        a_ = net.minecraft.u.E.a("entity.llama.hurt");
        gn = net.minecraft.u.E.a("entity.llama.spit");
        gU = net.minecraft.u.E.a("entity.llama.step");
        hX = net.minecraft.u.E.a("entity.llama.swag");
        hp = net.minecraft.u.E.a("entity.magmacube.death");
        es = net.minecraft.u.E.a("entity.magmacube.hurt");
        et = net.minecraft.u.E.a("entity.magmacube.jump");
        hA = net.minecraft.u.E.a("entity.magmacube.squish");
        eD = net.minecraft.u.E.a("block.metal.break");
        gi = net.minecraft.u.E.a("block.metal.fall");
        ft = net.minecraft.u.E.a("block.metal.hit");
        ax = net.minecraft.u.E.a("block.metal.place");
        bK = net.minecraft.u.E.a("block.metal_pressureplate.click_off");
        hD = net.minecraft.u.E.a("block.metal_pressureplate.click_on");
        dS = net.minecraft.u.E.a("block.metal.step");
        bg = net.minecraft.u.E.a("entity.minecart.inside");
        c7 = net.minecraft.u.E.a("entity.minecart.riding");
        aY = net.minecraft.u.E.a("entity.mooshroom.shear");
        bX = net.minecraft.u.E.a("entity.mule.ambient");
        eU = net.minecraft.u.E.a("entity.mule.chest");
        cR = net.minecraft.u.E.a("entity.mule.death");
        aB = net.minecraft.u.E.a("entity.mule.hurt");
        em = net.minecraft.u.E.a("music.creative");
        d7 = net.minecraft.u.E.a("music.credits");
        gM = net.minecraft.u.E.a("music.dragon");
        f7 = net.minecraft.u.E.a("music.end");
        a3 = net.minecraft.u.E.a("music.game");
        hh = net.minecraft.u.E.a("music.menu");
        dQ = net.minecraft.u.E.a("music.nether");
        aJ = net.minecraft.u.E.a("block.note.basedrum");
        e9 = net.minecraft.u.E.a("block.note.bass");
        u = net.minecraft.u.E.a("block.note.bell");
        dC = net.minecraft.u.E.a("block.note.chime");
        F = net.minecraft.u.E.a("block.note.flute");
        ea = net.minecraft.u.E.a("block.note.guitar");
        cE = net.minecraft.u.E.a("block.note.harp");
        P = net.minecraft.u.E.a("block.note.hat");
        bI = net.minecraft.u.E.a("block.note.pling");
        j = net.minecraft.u.E.a("block.note.snare");
        bz = net.minecraft.u.E.a("block.note.xylophone");
        gj = net.minecraft.u.E.a("entity.painting.break");
        hl = net.minecraft.u.E.a("entity.painting.place");
        bv = net.minecraft.u.E.a("entity.parrot.ambient");
        dz = net.minecraft.u.E.a("entity.parrot.death");
        db = net.minecraft.u.E.a("entity.parrot.eat");
        hW = net.minecraft.u.E.a("entity.parrot.fly");
        hF = net.minecraft.u.E.a("entity.parrot.hurt");
        g = net.minecraft.u.E.a("entity.parrot.imitate.blaze");
        at = net.minecraft.u.E.a("entity.parrot.imitate.creeper");
        fx = net.minecraft.u.E.a("entity.parrot.imitate.elder_guardian");
        bs = net.minecraft.u.E.a("entity.parrot.imitate.enderdragon");
        ay = net.minecraft.u.E.a("entity.parrot.imitate.enderman");
        bi = net.minecraft.u.E.a("entity.parrot.imitate.endermite");
        h4 = net.minecraft.u.E.a("entity.parrot.imitate.evocation_illager");
        cg = net.minecraft.u.E.a("entity.parrot.imitate.ghast");
        hb = net.minecraft.u.E.a("entity.parrot.imitate.husk");
        dg = net.minecraft.u.E.a("entity.parrot.imitate.illusion_illager");
        dk = net.minecraft.u.E.a("entity.parrot.imitate.magmacube");
        ag = net.minecraft.u.E.a("entity.parrot.imitate.polar_bear");
        c3 = net.minecraft.u.E.a("entity.parrot.imitate.shulker");
        w = net.minecraft.u.E.a("entity.parrot.imitate.silverfish");
        cB = net.minecraft.u.E.a("entity.parrot.imitate.skeleton");
        fs = net.minecraft.u.E.a("entity.parrot.imitate.slime");
        da = net.minecraft.u.E.a("entity.parrot.imitate.spider");
        cs = net.minecraft.u.E.a("entity.parrot.imitate.stray");
        b2 = net.minecraft.u.E.a("entity.parrot.imitate.vex");
        c = net.minecraft.u.E.a("entity.parrot.imitate.vindication_illager");
        hO = net.minecraft.u.E.a("entity.parrot.imitate.witch");
        ff = net.minecraft.u.E.a("entity.parrot.imitate.wither");
        hB = net.minecraft.u.E.a("entity.parrot.imitate.wither_skeleton");
        hy = net.minecraft.u.E.a("entity.parrot.imitate.wolf");
        ha = net.minecraft.u.E.a("entity.parrot.imitate.zombie");
        au = net.minecraft.u.E.a("entity.parrot.imitate.zombie_pigman");
        J = net.minecraft.u.E.a("entity.parrot.imitate.zombie_villager");
        bm = net.minecraft.u.E.a("entity.parrot.step");
        s = net.minecraft.u.E.a("entity.pig.ambient");
        fY = net.minecraft.u.E.a("entity.pig.death");
        fn = net.minecraft.u.E.a("entity.pig.hurt");
        dN = net.minecraft.u.E.a("entity.pig.saddle");
        gt = net.minecraft.u.E.a("entity.pig.step");
        e8 = net.minecraft.u.E.a("block.piston.contract");
        eu = net.minecraft.u.E.a("block.piston.extend");
        hV = net.minecraft.u.E.a("entity.player.attack.crit");
        cu = net.minecraft.u.E.a("entity.player.attack.knockback");
        eL = net.minecraft.u.E.a("entity.player.attack.nodamage");
        eb = net.minecraft.u.E.a("entity.player.attack.strong");
        l = net.minecraft.u.E.a("entity.player.attack.sweep");
        a2 = net.minecraft.u.E.a("entity.player.attack.weak");
        eA = net.minecraft.u.E.a("entity.player.big_fall");
        ho = net.minecraft.u.E.a("entity.player.breath");
        fF = net.minecraft.u.E.a("entity.player.burp");
        cn = net.minecraft.u.E.a("entity.player.death");
        fW = net.minecraft.u.E.a("entity.player.hurt");
        eT = net.minecraft.u.E.a("entity.player.hurt_drown");
        ds = net.minecraft.u.E.a("entity.player.hurt_on_fire");
        fa = net.minecraft.u.E.a("entity.player.levelup");
        E = net.minecraft.u.E.a("entity.player.small_fall");
        dj = net.minecraft.u.E.a("entity.player.splash");
        a5 = net.minecraft.u.E.a("entity.player.swim");
        fT = net.minecraft.u.E.a("entity.polar_bear.ambient");
        h2 = net.minecraft.u.E.a("entity.polar_bear.baby_ambient");
        fq = net.minecraft.u.E.a("entity.polar_bear.death");
        eQ = net.minecraft.u.E.a("entity.polar_bear.hurt");
        by = net.minecraft.u.E.a("entity.polar_bear.step");
        fm = net.minecraft.u.E.a("entity.polar_bear.warning");
        f6 = net.minecraft.u.E.a("block.portal.ambient");
        cD = net.minecraft.u.E.a("block.portal.travel");
        aq = net.minecraft.u.E.a("block.portal.trigger");
        bS = net.minecraft.u.E.a("entity.rabbit.ambient");
        a8 = net.minecraft.u.E.a("entity.rabbit.attack");
        x = net.minecraft.u.E.a("entity.rabbit.death");
        gh = net.minecraft.u.E.a("entity.rabbit.hurt");
        cN = net.minecraft.u.E.a("entity.rabbit.jump");
        dK = net.minecraft.u.E.a("record.11");
        dt = net.minecraft.u.E.a("record.13");
        hR = net.minecraft.u.E.a("record.blocks");
        ap = net.minecraft.u.E.a("record.cat");
        g_ = net.minecraft.u.E.a("record.chirp");
        el = net.minecraft.u.E.a("record.far");
        gy = net.minecraft.u.E.a("record.mall");
        fh = net.minecraft.u.E.a("record.mellohi");
        i = net.minecraft.u.E.a("record.stal");
        aR = net.minecraft.u.E.a("record.strad");
        dW = net.minecraft.u.E.a("record.wait");
        a4 = net.minecraft.u.E.a("record.ward");
        cZ = net.minecraft.u.E.a("block.redstone_torch.burnout");
        fz = net.minecraft.u.E.a("block.sand.break");
        I = net.minecraft.u.E.a("block.sand.fall");
        ga = net.minecraft.u.E.a("block.sand.hit");
        e0 = net.minecraft.u.E.a("block.sand.place");
        dG = net.minecraft.u.E.a("block.sand.step");
        gI = net.minecraft.u.E.a("entity.sheep.ambient");
        hE = net.minecraft.u.E.a("entity.sheep.death");
        e6 = net.minecraft.u.E.a("entity.sheep.hurt");
        d9 = net.minecraft.u.E.a("entity.sheep.shear");
        ao = net.minecraft.u.E.a("entity.sheep.step");
        fb = net.minecraft.u.E.a("item.shield.block");
        cl = net.minecraft.u.E.a("item.shield.break");
        hm = net.minecraft.u.E.a("item.shovel.flatten");
        aE = net.minecraft.u.E.a("entity.shulker.ambient");
        di = net.minecraft.u.E.a("block.shulker_box.close");
        gK = net.minecraft.u.E.a("block.shulker_box.open");
        bb = net.minecraft.u.E.a("entity.shulker_bullet.hit");
        N = net.minecraft.u.E.a("entity.shulker_bullet.hurt");
        c6 = net.minecraft.u.E.a("entity.shulker.close");
        gV = net.minecraft.u.E.a("entity.shulker.death");
        fG = net.minecraft.u.E.a("entity.shulker.hurt");
        eW = net.minecraft.u.E.a("entity.shulker.hurt_closed");
        r = net.minecraft.u.E.a("entity.shulker.open");
        g6 = net.minecraft.u.E.a("entity.shulker.shoot");
        dT = net.minecraft.u.E.a("entity.shulker.teleport");
        eK = net.minecraft.u.E.a("entity.silverfish.ambient");
        hf = net.minecraft.u.E.a("entity.silverfish.death");
        cG = net.minecraft.u.E.a("entity.silverfish.hurt");
        eg = net.minecraft.u.E.a("entity.silverfish.step");
        fr = net.minecraft.u.E.a("entity.skeleton.ambient");
        e7 = net.minecraft.u.E.a("entity.skeleton.death");
        cW = net.minecraft.u.E.a("entity.skeleton_horse.ambient");
        bV = net.minecraft.u.E.a("entity.skeleton_horse.death");
        b5 = net.minecraft.u.E.a("entity.skeleton_horse.hurt");
        b4 = net.minecraft.u.E.a("entity.skeleton.hurt");
        L = net.minecraft.u.E.a("entity.skeleton.shoot");
        dh = net.minecraft.u.E.a("entity.skeleton.step");
        gH = net.minecraft.u.E.a("entity.slime.attack");
        aW = net.minecraft.u.E.a("block.slime.break");
        ci = net.minecraft.u.E.a("entity.slime.death");
        eh = net.minecraft.u.E.a("block.slime.fall");
        f_ = net.minecraft.u.E.a("block.slime.hit");
        dJ = net.minecraft.u.E.a("entity.slime.hurt");
        fv = net.minecraft.u.E.a("entity.slime.jump");
        aQ = net.minecraft.u.E.a("block.slime.place");
        gd = net.minecraft.u.E.a("entity.slime.squish");
        al = net.minecraft.u.E.a("block.slime.step");
        hI = net.minecraft.u.E.a("entity.small_magmacube.death");
        fL = net.minecraft.u.E.a("entity.small_magmacube.hurt");
        eG = net.minecraft.u.E.a("entity.small_magmacube.squish");
        ba = net.minecraft.u.E.a("entity.small_slime.death");
        bG = net.minecraft.u.E.a("entity.small_slime.hurt");
        h3 = net.minecraft.u.E.a("entity.small_slime.jump");
        eB = net.minecraft.u.E.a("entity.small_slime.squish");
        hH = net.minecraft.u.E.a("entity.snowball.throw");
        D = net.minecraft.u.E.a("entity.snowman.ambient");
        dl = net.minecraft.u.E.a("entity.snowman.death");
        eO = net.minecraft.u.E.a("entity.snowman.hurt");
        fQ = net.minecraft.u.E.a("entity.snowman.shoot");
        gr = net.minecraft.u.E.a("block.snow.break");
        hn = net.minecraft.u.E.a("block.snow.fall");
        gL = net.minecraft.u.E.a("block.snow.hit");
        an = net.minecraft.u.E.a("block.snow.place");
        cf = net.minecraft.u.E.a("block.snow.step");
        hZ = net.minecraft.u.E.a("entity.spider.ambient");
        hw = net.minecraft.u.E.a("entity.spider.death");
        gb = net.minecraft.u.E.a("entity.spider.hurt");
        d5 = net.minecraft.u.E.a("entity.spider.step");
        cw = net.minecraft.u.E.a("entity.splash_potion.break");
        cU = net.minecraft.u.E.a("entity.splash_potion.throw");
        c2 = net.minecraft.u.E.a("entity.squid.ambient");
        am = net.minecraft.u.E.a("entity.squid.death");
        f2 = net.minecraft.u.E.a("entity.squid.hurt");
        W = net.minecraft.u.E.a("block.stone.break");
        dc = net.minecraft.u.E.a("block.stone_button.click_off");
        eo = net.minecraft.u.E.a("block.stone_button.click_on");
        gc = net.minecraft.u.E.a("block.stone.fall");
        gs = net.minecraft.u.E.a("block.stone.hit");
        f0 = net.minecraft.u.E.a("block.stone.place");
        hY = net.minecraft.u.E.a("block.stone_pressureplate.click_off");
        ct = net.minecraft.u.E.a("block.stone_pressureplate.click_on");
        hu = net.minecraft.u.E.a("block.stone.step");
        bA = net.minecraft.u.E.a("entity.stray.ambient");
        fB = net.minecraft.u.E.a("entity.stray.death");
        bC = net.minecraft.u.E.a("entity.stray.hurt");
        fu = net.minecraft.u.E.a("entity.stray.step");
        eV = net.minecraft.u.E.a("enchant.thorns.hit");
        ei = net.minecraft.u.E.a("entity.tnt.primed");
        cm = net.minecraft.u.E.a("item.totem.use");
        gB = net.minecraft.u.E.a("block.tripwire.attach");
        aP = net.minecraft.u.E.a("block.tripwire.click_off");
        cC = net.minecraft.u.E.a("block.tripwire.click_on");
        bo = net.minecraft.u.E.a("block.tripwire.detach");
        bN = net.minecraft.u.E.a("ui.button.click");
        aA = net.minecraft.u.E.a("ui.toast.in");
        af = net.minecraft.u.E.a("ui.toast.out");
        fM = net.minecraft.u.E.a("ui.toast.challenge_complete");
        aG = net.minecraft.u.E.a("entity.vex.ambient");
        ce = net.minecraft.u.E.a("entity.vex.charge");
        G = net.minecraft.u.E.a("entity.vex.death");
        bD = net.minecraft.u.E.a("entity.vex.hurt");
        bE = net.minecraft.u.E.a("entity.villager.ambient");
        eX = net.minecraft.u.E.a("entity.villager.death");
        T = net.minecraft.u.E.a("entity.villager.hurt");
        gS = net.minecraft.u.E.a("entity.villager.no");
        bR = net.minecraft.u.E.a("entity.villager.trading");
        X = net.minecraft.u.E.a("entity.villager.yes");
        eJ = net.minecraft.u.E.a("entity.vindication_illager.ambient");
        he = net.minecraft.u.E.a("entity.vindication_illager.death");
        aI = net.minecraft.u.E.a("entity.vindication_illager.hurt");
        cr = net.minecraft.u.E.a("block.waterlily.place");
        ac = net.minecraft.u.E.a("block.water.ambient");
        b0 = net.minecraft.u.E.a("weather.rain");
        a = net.minecraft.u.E.a("weather.rain.above");
        gv = net.minecraft.u.E.a("entity.witch.ambient");
        cz = net.minecraft.u.E.a("entity.witch.death");
        fV = net.minecraft.u.E.a("entity.witch.drink");
        gN = net.minecraft.u.E.a("entity.witch.hurt");
        g4 = net.minecraft.u.E.a("entity.witch.throw");
        fi = net.minecraft.u.E.a("entity.wither.ambient");
        ah = net.minecraft.u.E.a("entity.wither.break_block");
        aL = net.minecraft.u.E.a("entity.wither.death");
        e3 = net.minecraft.u.E.a("entity.wither.hurt");
        e4 = net.minecraft.u.E.a("entity.wither.shoot");
        ab = net.minecraft.u.E.a("entity.wither_skeleton.ambient");
        dD = net.minecraft.u.E.a("entity.wither_skeleton.death");
        fR = net.minecraft.u.E.a("entity.wither_skeleton.hurt");
        A = net.minecraft.u.E.a("entity.wither_skeleton.step");
        q = net.minecraft.u.E.a("entity.wither.spawn");
        bh = net.minecraft.u.E.a("entity.wolf.ambient");
        aj = net.minecraft.u.E.a("entity.wolf.death");
        eY = net.minecraft.u.E.a("entity.wolf.growl");
        ae = net.minecraft.u.E.a("entity.wolf.howl");
        g8 = net.minecraft.u.E.a("entity.wolf.hurt");
        bn = net.minecraft.u.E.a("entity.wolf.pant");
        fp = net.minecraft.u.E.a("entity.wolf.shake");
        gg = net.minecraft.u.E.a("entity.wolf.step");
        d4 = net.minecraft.u.E.a("entity.wolf.whine");
        dY = net.minecraft.u.E.a("block.wooden_door.close");
        bl = net.minecraft.u.E.a("block.wooden_door.open");
        cP = net.minecraft.u.E.a("block.wooden_trapdoor.close");
        fc = net.minecraft.u.E.a("block.wooden_trapdoor.open");
        gz = net.minecraft.u.E.a("block.wood.break");
        hv = net.minecraft.u.E.a("block.wood_button.click_off");
        eI = net.minecraft.u.E.a("block.wood_button.click_on");
        k = net.minecraft.u.E.a("block.wood.fall");
        hk = net.minecraft.u.E.a("block.wood.hit");
        gR = net.minecraft.u.E.a("block.wood.place");
        d0 = net.minecraft.u.E.a("block.wood_pressureplate.click_off");
        fA = net.minecraft.u.E.a("block.wood_pressureplate.click_on");
        M = net.minecraft.u.E.a("block.wood.step");
        dE = net.minecraft.u.E.a("entity.zombie.ambient");
        d_ = net.minecraft.u.E.a("entity.zombie.attack_door_wood");
        dX = net.minecraft.u.E.a("entity.zombie.attack_iron_door");
        a9 = net.minecraft.u.E.a("entity.zombie.break_door_wood");
        f8 = net.minecraft.u.E.a("entity.zombie.death");
        ca = net.minecraft.u.E.a("entity.zombie_horse.ambient");
        fK = net.minecraft.u.E.a("entity.zombie_horse.death");
        o = net.minecraft.u.E.a("entity.zombie_horse.hurt");
        aC = net.minecraft.u.E.a("entity.zombie.hurt");
        aw = net.minecraft.u.E.a("entity.zombie.infect");
        hN = net.minecraft.u.E.a("entity.zombie_pig.ambient");
        gC = net.minecraft.u.E.a("entity.zombie_pig.angry");
        g3 = net.minecraft.u.E.a("entity.zombie_pig.death");
        b9 = net.minecraft.u.E.a("entity.zombie_pig.hurt");
        aO = net.minecraft.u.E.a("entity.zombie.step");
        m = net.minecraft.u.E.a("entity.zombie_villager.ambient");
        fO = net.minecraft.u.E.a("entity.zombie_villager.converted");
        hd = net.minecraft.u.E.a("entity.zombie_villager.cure");
        ge = net.minecraft.u.E.a("entity.zombie_villager.death");
        co = net.minecraft.u.E.a("entity.zombie_villager.hurt");
        cO = net.minecraft.u.E.a("entity.zombie_villager.step");
    }

    private static d a(String string) {
        d d10 = net.minecraft.ar.d.c.a(new v(string));
        if (d10 == null) {
            throw new IllegalStateException("Invalid Sound requested: " + string);
        }
        return d10;
    }
}

