/*
 * Decompiled with CFR 0.150.
 * 
 * Could not load the following classes:
 *  com.google.common.collect.Sets
 *  javax.annotation.Nullable
 */
package net.minecraft.u;

import com.google.common.collect.Sets;
import java.util.Set;
import javax.annotation.Nullable;
import net.minecraft.W.K;
import net.minecraft.W.V;
import net.minecraft.W.X;
import net.minecraft.W.Y;
import net.minecraft.W.aB;
import net.minecraft.W.aE;
import net.minecraft.W.aF;
import net.minecraft.W.aG;
import net.minecraft.W.aL;
import net.minecraft.W.aX;
import net.minecraft.W.aY;
import net.minecraft.W.a_;
import net.minecraft.W.ac;
import net.minecraft.W.ag;
import net.minecraft.W.ah;
import net.minecraft.W.al;
import net.minecraft.W.ap;
import net.minecraft.W.av;
import net.minecraft.W.az;
import net.minecraft.W.b0;
import net.minecraft.W.b2;
import net.minecraft.W.b6;
import net.minecraft.W.bC;
import net.minecraft.W.bH;
import net.minecraft.W.bI;
import net.minecraft.W.bQ;
import net.minecraft.W.bT;
import net.minecraft.W.bV;
import net.minecraft.W.bg;
import net.minecraft.W.bm;
import net.minecraft.W.bz;
import net.minecraft.W.cW;
import net.minecraft.W.cu;
import net.minecraft.ar.v;
import net.minecraft.u.f;

public class g {
    public static final /* synthetic */ K j;
    public static final /* synthetic */ bz ag;
    public static final /* synthetic */ K ae;
    public static final /* synthetic */ K c5;
    public static final /* synthetic */ K cb;
    public static final /* synthetic */ cu U;
    public static final /* synthetic */ K W;
    public static final /* synthetic */ K c6;
    public static final /* synthetic */ K aS;
    public static final /* synthetic */ K bG;
    public static final /* synthetic */ K am;
    public static final /* synthetic */ K bf;
    public static final /* synthetic */ K aP;
    public static final /* synthetic */ K ai;
    public static final /* synthetic */ K cz;
    public static final /* synthetic */ K ba;
    public static final /* synthetic */ K bp;
    public static final /* synthetic */ K c4;
    public static final /* synthetic */ K dl;
    public static final /* synthetic */ K di;
    public static final /* synthetic */ K co;
    public static final /* synthetic */ a_ b6;
    public static final /* synthetic */ K cO;
    public static final /* synthetic */ K ab;
    public static final /* synthetic */ aY bY;
    public static final /* synthetic */ cu bO;
    public static final /* synthetic */ K h;
    public static final /* synthetic */ bH aU;
    public static final /* synthetic */ K bJ;
    public static final /* synthetic */ K aD;
    public static final /* synthetic */ bg cv;
    public static final /* synthetic */ K a_;
    public static final /* synthetic */ K aW;
    public static final /* synthetic */ K cp;
    public static final /* synthetic */ K bl;
    public static final /* synthetic */ K cR;
    public static final /* synthetic */ cu e;
    public static final /* synthetic */ cu F;
    public static final /* synthetic */ aG aH;
    public static final /* synthetic */ K cH;
    public static final /* synthetic */ aB p;
    public static final /* synthetic */ K aa;
    public static final /* synthetic */ K bR;
    public static final /* synthetic */ bC C;
    public static final /* synthetic */ K bE;
    public static final /* synthetic */ K dk;
    public static final /* synthetic */ K b2;
    public static final /* synthetic */ K bu;
    public static final /* synthetic */ K bP;
    public static final /* synthetic */ K c3;
    public static final /* synthetic */ K r;
    public static final /* synthetic */ K bv;
    public static final /* synthetic */ K ce;
    public static final /* synthetic */ K au;
    public static final /* synthetic */ K c0;
    public static final /* synthetic */ K bZ;
    public static final /* synthetic */ K aQ;
    public static final /* synthetic */ K dd;
    public static final /* synthetic */ K O;
    public static final /* synthetic */ K av;
    public static final /* synthetic */ K al;
    public static final /* synthetic */ K K;
    public static final /* synthetic */ al bW;
    public static final /* synthetic */ K ct;
    public static final /* synthetic */ K k;
    public static final /* synthetic */ K bj;
    public static final /* synthetic */ av b9;
    public static final /* synthetic */ K cK;
    public static final /* synthetic */ K w;
    public static final /* synthetic */ K ah;
    public static final /* synthetic */ K G;
    public static final /* synthetic */ cu H;
    public static final /* synthetic */ K l;
    public static final /* synthetic */ K V;
    public static final /* synthetic */ K ax;
    public static final /* synthetic */ K c8;
    public static final /* synthetic */ K a2;
    public static final /* synthetic */ K cU;
    public static final /* synthetic */ K as;
    public static final /* synthetic */ K ad;
    public static final /* synthetic */ K cD;
    public static final /* synthetic */ K a7;
    public static final /* synthetic */ Y z;
    public static final /* synthetic */ ap cS;
    public static final /* synthetic */ K Z;
    public static final /* synthetic */ aE cZ;
    public static final /* synthetic */ K ak;
    private static final /* synthetic */ Set<K> b_;
    public static final /* synthetic */ K aR;
    public static final /* synthetic */ aL M;
    public static final /* synthetic */ K dp;
    public static final /* synthetic */ K a;
    public static final /* synthetic */ K bs;
    public static final /* synthetic */ K aK;
    public static final /* synthetic */ K bk;
    public static final /* synthetic */ K b3;
    public static final /* synthetic */ K y;
    public static final /* synthetic */ V aN;
    public static final /* synthetic */ K b5;
    public static final /* synthetic */ K B;
    public static final /* synthetic */ ag ac;
    public static final /* synthetic */ K br;
    public static final /* synthetic */ K cs;
    public static final /* synthetic */ K b4;
    public static final /* synthetic */ K I;
    public static final /* synthetic */ K o;
    public static final /* synthetic */ K bd;
    public static final /* synthetic */ K ap;
    public static final /* synthetic */ K df;
    public static final /* synthetic */ K db;
    public static final /* synthetic */ K aT;
    public static final /* synthetic */ K D;
    public static final /* synthetic */ K aE;
    public static final /* synthetic */ cu at;
    public static final /* synthetic */ K ca;
    public static final /* synthetic */ K a6;
    public static final /* synthetic */ K a1;
    public static final /* synthetic */ K n;
    public static final /* synthetic */ K c7;
    public static final /* synthetic */ K aL;
    public static final /* synthetic */ K N;
    public static final /* synthetic */ K bb;
    public static final /* synthetic */ bz cL;
    public static final /* synthetic */ K cB;
    public static final /* synthetic */ K cN;
    public static final /* synthetic */ K dh;
    public static final /* synthetic */ bV bB;
    public static final /* synthetic */ K bC;
    public static final /* synthetic */ K ck;
    public static final /* synthetic */ K t;
    public static final /* synthetic */ K cA;
    public static final /* synthetic */ bm a8;
    public static final /* synthetic */ K cX;
    public static final /* synthetic */ K b7;
    public static final /* synthetic */ K aG;
    public static final /* synthetic */ K i;
    public static final /* synthetic */ K bI;
    public static final /* synthetic */ K bV;
    public static final /* synthetic */ K cG;
    public static final /* synthetic */ b2 S;
    public static final /* synthetic */ K ch;
    public static final /* synthetic */ K P;
    public static final /* synthetic */ bQ bK;
    public static final /* synthetic */ K cT;
    public static final /* synthetic */ cW b;
    public static final /* synthetic */ K bw;
    public static final /* synthetic */ K J;
    public static final /* synthetic */ K an;
    public static final /* synthetic */ K bz;
    public static final /* synthetic */ K ay;
    public static final /* synthetic */ K aC;
    public static final /* synthetic */ bV ar;
    public static final /* synthetic */ K d;
    public static final /* synthetic */ aE cj;
    public static final /* synthetic */ K q;
    public static final /* synthetic */ bT cP;
    public static final /* synthetic */ K bn;
    public static final /* synthetic */ b2 bU;
    public static final /* synthetic */ bT aV;
    public static final /* synthetic */ b6 aO;
    public static final /* synthetic */ K a0;
    public static final /* synthetic */ K cW;
    public static final /* synthetic */ K bc;
    public static final /* synthetic */ K Y;
    public static final /* synthetic */ K b8;
    public static final /* synthetic */ K x;
    public static final /* synthetic */ K ci;
    public static final /* synthetic */ K de;
    public static final /* synthetic */ K c2;
    public static final /* synthetic */ b0 bq;
    public static final /* synthetic */ K ao;
    public static final /* synthetic */ K cC;
    public static final /* synthetic */ K cx;
    public static final /* synthetic */ aB cl;
    public static final /* synthetic */ K bD;
    public static final /* synthetic */ K v;
    public static final /* synthetic */ K X;
    public static final /* synthetic */ X a5;
    public static final /* synthetic */ az cd;
    public static final /* synthetic */ K aB;
    public static final /* synthetic */ K bh;
    public static final /* synthetic */ K af;
    public static final /* synthetic */ K dg;
    public static final /* synthetic */ K dj;
    public static final /* synthetic */ K dn;
    public static final /* synthetic */ cu bS;
    public static final /* synthetic */ a_ cQ;
    public static final /* synthetic */ K by;
    public static final /* synthetic */ K da;
    public static final /* synthetic */ K u;
    public static final /* synthetic */ K bg;
    public static final /* synthetic */ K aX;
    public static final /* synthetic */ K aM;
    public static final /* synthetic */ aB cV;
    public static final /* synthetic */ K cy;
    public static final /* synthetic */ K aF;
    public static final /* synthetic */ K cf;
    private static /* synthetic */ boolean c9;
    public static final /* synthetic */ K bF;
    public static final /* synthetic */ K cq;
    public static final /* synthetic */ aB aJ;
    public static final /* synthetic */ K cF;
    public static final /* synthetic */ K cE;
    public static final /* synthetic */ K dm;
    public static final /* synthetic */ K aI;
    public static final /* synthetic */ bI aZ;
    public static final /* synthetic */ K g;
    public static final /* synthetic */ K cm;
    public static final /* synthetic */ aF aA;
    public static final /* synthetic */ ah bX;
    public static final /* synthetic */ K cw;
    public static final /* synthetic */ K m;
    public static final /* synthetic */ K cJ;
    public static final /* synthetic */ K cI;
    public static final /* synthetic */ K bt;
    public static final /* synthetic */ K a4;
    public static final /* synthetic */ K s;
    public static final /* synthetic */ ac bi;
    public static final /* synthetic */ K az;
    public static final /* synthetic */ K aY;
    public static final /* synthetic */ aB c;
    public static final /* synthetic */ K bx;
    public static final /* synthetic */ K b0;
    public static final /* synthetic */ K a9;
    public static final /* synthetic */ K bN;
    public static final /* synthetic */ K L;
    public static final /* synthetic */ K Q;
    public static final /* synthetic */ K cY;
    public static final /* synthetic */ K bA;
    public static final /* synthetic */ cu f;
    public static final /* synthetic */ Y cg;
    public static final /* synthetic */ K aw;
    public static final /* synthetic */ K cM;
    public static final /* synthetic */ K cc;
    public static final /* synthetic */ K A;
    public static final /* synthetic */ K cu;
    public static final /* synthetic */ K be;
    public static final /* synthetic */ aB bT;
    public static final /* synthetic */ K aj;
    public static final /* synthetic */ K bo;
    public static final /* synthetic */ K c1;
    public static final /* synthetic */ K bH;
    public static final /* synthetic */ K cn;
    public static final /* synthetic */ K E;
    public static final /* synthetic */ K R;
    public static final /* synthetic */ K c_;
    public static final /* synthetic */ K a3;
    public static final /* synthetic */ aB bL;
    public static final /* synthetic */ b0 bQ;
    public static final /* synthetic */ aL cr;
    public static final /* synthetic */ K bM;
    public static final /* synthetic */ K T;
    public static final /* synthetic */ K b1;
    public static final /* synthetic */ K bm;
    public static final /* synthetic */ aX dc;
    public static final /* synthetic */ K aq;

    @Nullable
    private static K a(String string) {
        K k2 = net.minecraft.W.K.h.a(new v(string));
        if (!b_.add(k2)) {
            throw new IllegalStateException("Invalid Block requested: " + string);
        }
        return k2;
    }

    static {
        if (net.minecraft.u.g.a()) {
            net.minecraft.u.g.b(true);
        }
        if (!net.minecraft.u.f.b()) {
            throw new RuntimeException("Accessed Blocks before Bootstrap!");
        }
        b_ = Sets.newHashSet();
        bf = net.minecraft.u.g.a("air");
        bx = net.minecraft.u.g.a("stone");
        aU = (bH)net.minecraft.u.g.a("grass");
        bv = net.minecraft.u.g.a("dirt");
        cW = net.minecraft.u.g.a("cobblestone");
        cB = net.minecraft.u.g.a("planks");
        dj = net.minecraft.u.g.a("sapling");
        g = net.minecraft.u.g.a("bedrock");
        cL = (bz)net.minecraft.u.g.a("flowing_water");
        bQ = (b0)net.minecraft.u.g.a("water");
        ag = (bz)net.minecraft.u.g.a("flowing_lava");
        bq = (b0)net.minecraft.u.g.a("lava");
        aO = (b6)net.minecraft.u.g.a("sand");
        di = net.minecraft.u.g.a("gravel");
        aK = net.minecraft.u.g.a("gold_ore");
        ak = net.minecraft.u.g.a("iron_ore");
        l = net.minecraft.u.g.a("coal_ore");
        bu = net.minecraft.u.g.a("log");
        aB = net.minecraft.u.g.a("log2");
        bU = (b2)net.minecraft.u.g.a("leaves");
        S = (b2)net.minecraft.u.g.a("leaves2");
        a2 = net.minecraft.u.g.a("sponge");
        a = net.minecraft.u.g.a("glass");
        aC = net.minecraft.u.g.a("lapis_ore");
        av = net.minecraft.u.g.a("lapis_block");
        n = net.minecraft.u.g.a("dispenser");
        bC = net.minecraft.u.g.a("sandstone");
        dm = net.minecraft.u.g.a("noteblock");
        R = net.minecraft.u.g.a("bed");
        w = net.minecraft.u.g.a("golden_rail");
        aY = net.minecraft.u.g.a("detector_rail");
        M = (aL)net.minecraft.u.g.a("sticky_piston");
        dh = net.minecraft.u.g.a("web");
        dc = (aX)net.minecraft.u.g.a("tallgrass");
        b9 = (av)net.minecraft.u.g.a("deadbush");
        cr = (aL)net.minecraft.u.g.a("piston");
        bi = (ac)net.minecraft.u.g.a("piston_head");
        s = net.minecraft.u.g.a("wool");
        cS = (ap)net.minecraft.u.g.a("piston_extension");
        cZ = (aE)net.minecraft.u.g.a("yellow_flower");
        cj = (aE)net.minecraft.u.g.a("red_flower");
        cg = (Y)net.minecraft.u.g.a("brown_mushroom");
        z = (Y)net.minecraft.u.g.a("red_mushroom");
        a7 = net.minecraft.u.g.a("gold_block");
        E = net.minecraft.u.g.a("iron_block");
        H = (cu)net.minecraft.u.g.a("double_stone_slab");
        bO = (cu)net.minecraft.u.g.a("stone_slab");
        cY = net.minecraft.u.g.a("brick_block");
        cR = net.minecraft.u.g.a("tnt");
        c8 = net.minecraft.u.g.a("bookshelf");
        x = net.minecraft.u.g.a("mossy_cobblestone");
        bP = net.minecraft.u.g.a("obsidian");
        h = net.minecraft.u.g.a("torch");
        C = (bC)net.minecraft.u.g.a("fire");
        i = net.minecraft.u.g.a("mob_spawner");
        aX = net.minecraft.u.g.a("oak_stairs");
        cd = (az)net.minecraft.u.g.a("chest");
        bK = (bQ)net.minecraft.u.g.a("redstone_wire");
        cO = net.minecraft.u.g.a("diamond_ore");
        bF = net.minecraft.u.g.a("diamond_block");
        aj = net.minecraft.u.g.a("crafting_table");
        c3 = net.minecraft.u.g.a("wheat");
        cU = net.minecraft.u.g.a("farmland");
        bJ = net.minecraft.u.g.a("furnace");
        bn = net.minecraft.u.g.a("lit_furnace");
        aR = net.minecraft.u.g.a("standing_sign");
        aJ = (aB)net.minecraft.u.g.a("wooden_door");
        bT = (aB)net.minecraft.u.g.a("spruce_door");
        cV = (aB)net.minecraft.u.g.a("birch_door");
        c = (aB)net.minecraft.u.g.a("jungle_door");
        cl = (aB)net.minecraft.u.g.a("acacia_door");
        p = (aB)net.minecraft.u.g.a("dark_oak_door");
        cD = net.minecraft.u.g.a("ladder");
        bM = net.minecraft.u.g.a("rail");
        a0 = net.minecraft.u.g.a("stone_stairs");
        b0 = net.minecraft.u.g.a("wall_sign");
        ao = net.minecraft.u.g.a("lever");
        dl = net.minecraft.u.g.a("stone_pressure_plate");
        bL = (aB)net.minecraft.u.g.a("iron_door");
        bc = net.minecraft.u.g.a("wooden_pressure_plate");
        cu = net.minecraft.u.g.a("redstone_ore");
        cy = net.minecraft.u.g.a("lit_redstone_ore");
        ai = net.minecraft.u.g.a("unlit_redstone_torch");
        c5 = net.minecraft.u.g.a("redstone_torch");
        aI = net.minecraft.u.g.a("stone_button");
        o = net.minecraft.u.g.a("snow_layer");
        cF = net.minecraft.u.g.a("ice");
        da = net.minecraft.u.g.a("snow");
        aA = (aF)net.minecraft.u.g.a("cactus");
        d = net.minecraft.u.g.a("clay");
        aZ = (bI)net.minecraft.u.g.a("reeds");
        ct = net.minecraft.u.g.a("jukebox");
        bt = net.minecraft.u.g.a("fence");
        cN = net.minecraft.u.g.a("spruce_fence");
        q = net.minecraft.u.g.a("birch_fence");
        bd = net.minecraft.u.g.a("jungle_fence");
        bs = net.minecraft.u.g.a("dark_oak_fence");
        aa = net.minecraft.u.g.a("acacia_fence");
        G = net.minecraft.u.g.a("pumpkin");
        j = net.minecraft.u.g.a("netherrack");
        br = net.minecraft.u.g.a("soul_sand");
        W = net.minecraft.u.g.a("glowstone");
        aN = (V)net.minecraft.u.g.a("portal");
        y = net.minecraft.u.g.a("lit_pumpkin");
        b7 = net.minecraft.u.g.a("cake");
        bB = (bV)net.minecraft.u.g.a("unpowered_repeater");
        ar = (bV)net.minecraft.u.g.a("powered_repeater");
        cI = net.minecraft.u.g.a("trapdoor");
        be = net.minecraft.u.g.a("monster_egg");
        ay = net.minecraft.u.g.a("stonebrick");
        a1 = net.minecraft.u.g.a("brown_mushroom_block");
        db = net.minecraft.u.g.a("red_mushroom_block");
        dd = net.minecraft.u.g.a("iron_bars");
        a6 = net.minecraft.u.g.a("glass_pane");
        ae = net.minecraft.u.g.a("melon_block");
        Q = net.minecraft.u.g.a("pumpkin_stem");
        aM = net.minecraft.u.g.a("melon_stem");
        aW = net.minecraft.u.g.a("vine");
        dp = net.minecraft.u.g.a("fence_gate");
        aq = net.minecraft.u.g.a("spruce_fence_gate");
        O = net.minecraft.u.g.a("birch_fence_gate");
        cJ = net.minecraft.u.g.a("jungle_fence_gate");
        cC = net.minecraft.u.g.a("dark_oak_fence_gate");
        bI = net.minecraft.u.g.a("acacia_fence_gate");
        cG = net.minecraft.u.g.a("brick_stairs");
        cX = net.minecraft.u.g.a("stone_brick_stairs");
        a8 = (bm)net.minecraft.u.g.a("mycelium");
        c_ = net.minecraft.u.g.a("waterlily");
        dk = net.minecraft.u.g.a("nether_brick");
        dn = net.minecraft.u.g.a("nether_brick_fence");
        aP = net.minecraft.u.g.a("nether_brick_stairs");
        cE = net.minecraft.u.g.a("nether_wart");
        bH = net.minecraft.u.g.a("enchanting_table");
        B = net.minecraft.u.g.a("brewing_stand");
        aH = (aG)net.minecraft.u.g.a("cauldron");
        df = net.minecraft.u.g.a("end_portal");
        ad = net.minecraft.u.g.a("end_portal_frame");
        v = net.minecraft.u.g.a("end_stone");
        bG = net.minecraft.u.g.a("dragon_egg");
        as = net.minecraft.u.g.a("redstone_lamp");
        bp = net.minecraft.u.g.a("lit_redstone_lamp");
        f = (cu)net.minecraft.u.g.a("double_wooden_slab");
        e = (cu)net.minecraft.u.g.a("wooden_slab");
        cT = net.minecraft.u.g.a("cocoa");
        ch = net.minecraft.u.g.a("sandstone_stairs");
        au = net.minecraft.u.g.a("emerald_ore");
        ba = net.minecraft.u.g.a("ender_chest");
        b = (cW)net.minecraft.u.g.a("tripwire_hook");
        cM = net.minecraft.u.g.a("tripwire");
        cs = net.minecraft.u.g.a("emerald_block");
        aT = net.minecraft.u.g.a("spruce_stairs");
        bA = net.minecraft.u.g.a("birch_stairs");
        al = net.minecraft.u.g.a("jungle_stairs");
        de = net.minecraft.u.g.a("command_block");
        bX = (ah)net.minecraft.u.g.a("beacon");
        bl = net.minecraft.u.g.a("cobblestone_wall");
        cA = net.minecraft.u.g.a("flower_pot");
        b4 = net.minecraft.u.g.a("carrots");
        ca = net.minecraft.u.g.a("potatoes");
        I = net.minecraft.u.g.a("wooden_button");
        bY = (aY)net.minecraft.u.g.a("skull");
        cb = net.minecraft.u.g.a("anvil");
        c4 = net.minecraft.u.g.a("trapped_chest");
        cH = net.minecraft.u.g.a("light_weighted_pressure_plate");
        cp = net.minecraft.u.g.a("heavy_weighted_pressure_plate");
        cP = (bT)net.minecraft.u.g.a("unpowered_comparator");
        aV = (bT)net.minecraft.u.g.a("powered_comparator");
        cQ = (a_)net.minecraft.u.g.a("daylight_detector");
        b6 = (a_)net.minecraft.u.g.a("daylight_detector_inverted");
        b8 = net.minecraft.u.g.a("redstone_block");
        u = net.minecraft.u.g.a("quartz_ore");
        ac = (ag)net.minecraft.u.g.a("hopper");
        k = net.minecraft.u.g.a("quartz_block");
        bN = net.minecraft.u.g.a("quartz_stairs");
        az = net.minecraft.u.g.a("activator_rail");
        cw = net.minecraft.u.g.a("dropper");
        ck = net.minecraft.u.g.a("stained_hardened_clay");
        ah = net.minecraft.u.g.a("barrier");
        bV = net.minecraft.u.g.a("iron_trapdoor");
        aL = net.minecraft.u.g.a("hay_block");
        D = net.minecraft.u.g.a("carpet");
        an = net.minecraft.u.g.a("hardened_clay");
        r = net.minecraft.u.g.a("coal_block");
        cq = net.minecraft.u.g.a("packed_ice");
        co = net.minecraft.u.g.a("acacia_stairs");
        am = net.minecraft.u.g.a("dark_oak_stairs");
        t = net.minecraft.u.g.a("slime");
        bW = (al)net.minecraft.u.g.a("double_plant");
        a5 = (X)net.minecraft.u.g.a("stained_glass");
        cv = (bg)net.minecraft.u.g.a("stained_glass_pane");
        cz = net.minecraft.u.g.a("prismarine");
        af = net.minecraft.u.g.a("sea_lantern");
        a4 = net.minecraft.u.g.a("standing_banner");
        aG = net.minecraft.u.g.a("wall_banner");
        aQ = net.minecraft.u.g.a("red_sandstone");
        bE = net.minecraft.u.g.a("red_sandstone_stairs");
        at = (cu)net.minecraft.u.g.a("double_stone_slab2");
        U = (cu)net.minecraft.u.g.a("stone_slab2");
        aD = net.minecraft.u.g.a("end_rod");
        cm = net.minecraft.u.g.a("chorus_plant");
        P = net.minecraft.u.g.a("chorus_flower");
        aF = net.minecraft.u.g.a("purpur_block");
        V = net.minecraft.u.g.a("purpur_pillar");
        a_ = net.minecraft.u.g.a("purpur_stairs");
        bS = (cu)net.minecraft.u.g.a("purpur_double_slab");
        F = (cu)net.minecraft.u.g.a("purpur_slab");
        dg = net.minecraft.u.g.a("end_bricks");
        K = net.minecraft.u.g.a("beetroots");
        ci = net.minecraft.u.g.a("grass_path");
        m = net.minecraft.u.g.a("end_gateway");
        aS = net.minecraft.u.g.a("repeating_command_block");
        bZ = net.minecraft.u.g.a("chain_command_block");
        bj = net.minecraft.u.g.a("frosted_ice");
        bR = net.minecraft.u.g.a("magma");
        bz = net.minecraft.u.g.a("nether_wart_block");
        Z = net.minecraft.u.g.a("red_nether_brick");
        bm = net.minecraft.u.g.a("bone_block");
        Y = net.minecraft.u.g.a("structure_void");
        ce = net.minecraft.u.g.a("observer");
        b1 = net.minecraft.u.g.a("white_shulker_box");
        bk = net.minecraft.u.g.a("orange_shulker_box");
        X = net.minecraft.u.g.a("magenta_shulker_box");
        L = net.minecraft.u.g.a("light_blue_shulker_box");
        aE = net.minecraft.u.g.a("yellow_shulker_box");
        bo = net.minecraft.u.g.a("lime_shulker_box");
        bh = net.minecraft.u.g.a("pink_shulker_box");
        J = net.minecraft.u.g.a("gray_shulker_box");
        ap = net.minecraft.u.g.a("silver_shulker_box");
        bg = net.minecraft.u.g.a("cyan_shulker_box");
        b5 = net.minecraft.u.g.a("purple_shulker_box");
        N = net.minecraft.u.g.a("blue_shulker_box");
        by = net.minecraft.u.g.a("brown_shulker_box");
        cx = net.minecraft.u.g.a("green_shulker_box");
        bw = net.minecraft.u.g.a("red_shulker_box");
        a3 = net.minecraft.u.g.a("black_shulker_box");
        c7 = net.minecraft.u.g.a("white_glazed_terracotta");
        A = net.minecraft.u.g.a("orange_glazed_terracotta");
        bb = net.minecraft.u.g.a("magenta_glazed_terracotta");
        c0 = net.minecraft.u.g.a("light_blue_glazed_terracotta");
        cn = net.minecraft.u.g.a("yellow_glazed_terracotta");
        b3 = net.minecraft.u.g.a("lime_glazed_terracotta");
        cf = net.minecraft.u.g.a("pink_glazed_terracotta");
        b2 = net.minecraft.u.g.a("gray_glazed_terracotta");
        cc = net.minecraft.u.g.a("silver_glazed_terracotta");
        a9 = net.minecraft.u.g.a("cyan_glazed_terracotta");
        T = net.minecraft.u.g.a("purple_glazed_terracotta");
        c1 = net.minecraft.u.g.a("blue_glazed_terracotta");
        ab = net.minecraft.u.g.a("brown_glazed_terracotta");
        ax = net.minecraft.u.g.a("green_glazed_terracotta");
        c2 = net.minecraft.u.g.a("red_glazed_terracotta");
        c6 = net.minecraft.u.g.a("black_glazed_terracotta");
        cK = net.minecraft.u.g.a("concrete");
        aw = net.minecraft.u.g.a("concrete_powder");
        bD = net.minecraft.u.g.a("structure_block");
        b_.clear();
    }

    private static IllegalStateException a(IllegalStateException illegalStateException) {
        return illegalStateException;
    }

    public static boolean b() {
        return c9;
    }

    public static boolean a() {
        boolean bl2 = net.minecraft.u.g.b();
        return !bl2;
    }

    public static void b(boolean bl2) {
        c9 = bl2;
    }
}

