/*
 * Decompiled with CFR 0.150.
 */
package net.minecraft.u;

import net.minecraft.ar.v;
import net.minecraft.k.m;
import net.minecraft.u.f;
import net.minecraft.w.H;
import net.minecraft.w.aF;
import net.minecraft.w.aW;
import net.minecraft.w.an;
import net.minecraft.w.ao;
import net.minecraft.w.au;
import net.minecraft.w.k;
import net.minecraft.w.n;

public class h {
    public static final /* synthetic */ net.minecraft.w.m D;
    public static final /* synthetic */ k M;
    public static final /* synthetic */ k g;
    public static final /* synthetic */ k cu;
    public static final /* synthetic */ k bX;
    public static final /* synthetic */ k bJ;
    public static final /* synthetic */ k aY;
    public static final /* synthetic */ net.minecraft.w.m b_;
    public static final /* synthetic */ k bp;
    public static final /* synthetic */ k bx;
    public static final /* synthetic */ k F;
    public static final /* synthetic */ k cq;
    public static final /* synthetic */ k ai;
    public static final /* synthetic */ k B;
    public static final /* synthetic */ k T;
    public static final /* synthetic */ k b0;
    public static final /* synthetic */ k az;
    public static final /* synthetic */ k cz;
    public static final /* synthetic */ k aO;
    public static final /* synthetic */ k bA;
    public static final /* synthetic */ k cv;
    public static final /* synthetic */ k b4;
    public static final /* synthetic */ k bV;
    public static final /* synthetic */ net.minecraft.w.m cy;
    public static final /* synthetic */ net.minecraft.w.m aK;
    public static final /* synthetic */ k cx;
    public static final /* synthetic */ k aB;
    public static final /* synthetic */ k al;
    public static final /* synthetic */ net.minecraft.w.m cs;
    public static final /* synthetic */ k aC;
    public static final /* synthetic */ k bB;
    public static final /* synthetic */ k C;
    public static final /* synthetic */ aW aT;
    public static final /* synthetic */ k ao;
    public static final /* synthetic */ k aQ;
    public static final /* synthetic */ k co;
    public static final /* synthetic */ k cd;
    public static final /* synthetic */ ao V;
    public static final /* synthetic */ net.minecraft.w.m an;
    public static final /* synthetic */ k aZ;
    public static final /* synthetic */ k bh;
    public static final /* synthetic */ net.minecraft.w.m w;
    public static final /* synthetic */ ao W;
    public static final /* synthetic */ k G;
    public static final /* synthetic */ k a6;
    public static final /* synthetic */ k s;
    public static final /* synthetic */ k bc;
    private static /* synthetic */ m[] cB;
    public static final /* synthetic */ k b5;
    public static final /* synthetic */ k cG;
    public static final /* synthetic */ k ah;
    public static final /* synthetic */ net.minecraft.w.m bD;
    public static final /* synthetic */ k by;
    public static final /* synthetic */ k bu;
    public static final /* synthetic */ k be;
    public static final /* synthetic */ k ax;
    public static final /* synthetic */ k X;
    public static final /* synthetic */ k Z;
    public static final /* synthetic */ k cc;
    public static final /* synthetic */ k aX;
    public static final /* synthetic */ k bl;
    public static final /* synthetic */ k e;
    public static final /* synthetic */ k a3;
    public static final /* synthetic */ k cA;
    public static final /* synthetic */ k aV;
    public static final /* synthetic */ k aP;
    public static final /* synthetic */ k bL;
    public static final /* synthetic */ k aW;
    public static final /* synthetic */ k bt;
    public static final /* synthetic */ net.minecraft.w.m H;
    public static final /* synthetic */ k r;
    public static final /* synthetic */ k t;
    public static final /* synthetic */ k aR;
    public static final /* synthetic */ k a0;
    public static final /* synthetic */ net.minecraft.w.m bP;
    public static final /* synthetic */ k bq;
    public static final /* synthetic */ k bw;
    public static final /* synthetic */ k au;
    public static final /* synthetic */ net.minecraft.w.m E;
    public static final /* synthetic */ k z;
    public static final /* synthetic */ k ay;
    public static final /* synthetic */ H i;
    public static final /* synthetic */ k U;
    public static final /* synthetic */ k a;
    public static final /* synthetic */ k b7;
    public static final /* synthetic */ k bk;
    public static final /* synthetic */ k a7;
    public static final /* synthetic */ au bQ;
    public static final /* synthetic */ k ag;
    public static final /* synthetic */ k cj;
    public static final /* synthetic */ k Q;
    public static final /* synthetic */ k O;
    public static final /* synthetic */ k aH;
    public static final /* synthetic */ k cp;
    public static final /* synthetic */ k aF;
    public static final /* synthetic */ k u;
    public static final /* synthetic */ k ch;
    public static final /* synthetic */ k x;
    public static final /* synthetic */ k l;
    public static final /* synthetic */ k aq;
    public static final /* synthetic */ aF Y;
    public static final /* synthetic */ k bR;
    public static final /* synthetic */ k aE;
    public static final /* synthetic */ k ce;
    public static final /* synthetic */ k b1;
    public static final /* synthetic */ k ca;
    public static final /* synthetic */ k aw;
    public static final /* synthetic */ k cE;
    public static final /* synthetic */ k bi;
    public static final /* synthetic */ k bU;
    public static final /* synthetic */ k P;
    public static final /* synthetic */ k q;
    public static final /* synthetic */ k v;
    public static final /* synthetic */ k ci;
    public static final /* synthetic */ net.minecraft.w.m cF;
    public static final /* synthetic */ k b;
    public static final /* synthetic */ k bs;
    public static final /* synthetic */ k a8;
    public static final /* synthetic */ k bH;
    public static final /* synthetic */ net.minecraft.w.m a4;
    public static final /* synthetic */ k bO;
    public static final /* synthetic */ k m;
    public static final /* synthetic */ k bG;
    public static final /* synthetic */ k bK;
    public static final /* synthetic */ k ap;
    public static final /* synthetic */ k a5;
    public static final /* synthetic */ k aM;
    public static final /* synthetic */ k bd;
    public static final /* synthetic */ k f;
    public static final /* synthetic */ k h;
    public static final /* synthetic */ k ac;
    public static final /* synthetic */ k bN;
    public static final /* synthetic */ k cr;
    public static final /* synthetic */ net.minecraft.w.m ab;
    public static final /* synthetic */ k k;
    public static final /* synthetic */ k bE;
    public static final /* synthetic */ an a9;
    public static final /* synthetic */ k a1;
    public static final /* synthetic */ k bm;
    public static final /* synthetic */ k j;
    public static final /* synthetic */ k aN;
    public static final /* synthetic */ k o;
    public static final /* synthetic */ k bM;
    public static final /* synthetic */ k aD;
    public static final /* synthetic */ k aL;
    public static final /* synthetic */ k ba;
    public static final /* synthetic */ k bo;
    public static final /* synthetic */ k cw;
    public static final /* synthetic */ ao b3;
    public static final /* synthetic */ k as;
    public static final /* synthetic */ k bY;
    public static final /* synthetic */ k b8;
    public static final /* synthetic */ net.minecraft.w.m bv;
    public static final /* synthetic */ k br;
    public static final /* synthetic */ k aU;
    public static final /* synthetic */ k aJ;
    public static final /* synthetic */ k bT;
    public static final /* synthetic */ k aI;
    public static final /* synthetic */ k cf;
    public static final /* synthetic */ k bS;
    public static final /* synthetic */ k R;
    public static final /* synthetic */ k cg;
    public static final /* synthetic */ k cD;
    public static final /* synthetic */ k N;
    public static final /* synthetic */ k am;
    public static final /* synthetic */ k bg;
    public static final /* synthetic */ k bF;
    public static final /* synthetic */ k ak;
    public static final /* synthetic */ k bf;
    public static final /* synthetic */ k bI;
    public static final /* synthetic */ k aj;
    public static final /* synthetic */ net.minecraft.w.m af;
    public static final /* synthetic */ k ad;
    public static final /* synthetic */ k bZ;
    public static final /* synthetic */ k aS;
    public static final /* synthetic */ k ae;
    public static final /* synthetic */ k av;
    public static final /* synthetic */ k ct;
    public static final /* synthetic */ k cl;
    public static final /* synthetic */ net.minecraft.w.m p;
    public static final /* synthetic */ k bz;
    public static final /* synthetic */ net.minecraft.w.m K;
    public static final /* synthetic */ k aA;
    public static final /* synthetic */ k c;
    public static final /* synthetic */ k J;
    public static final /* synthetic */ k bn;
    public static final /* synthetic */ k bb;
    public static final /* synthetic */ k a_;
    public static final /* synthetic */ k I;
    public static final /* synthetic */ k cb;
    public static final /* synthetic */ k A;
    public static final /* synthetic */ k b2;
    public static final /* synthetic */ net.minecraft.w.m S;
    public static final /* synthetic */ k ar;
    public static final /* synthetic */ k n;
    public static final /* synthetic */ k b6;
    public static final /* synthetic */ k aG;
    public static final /* synthetic */ k a2;
    public static final /* synthetic */ k cm;
    public static final /* synthetic */ k bW;
    public static final /* synthetic */ k bj;
    public static final /* synthetic */ k cn;
    public static final /* synthetic */ k at;
    public static final /* synthetic */ k y;
    public static final /* synthetic */ n d;
    public static final /* synthetic */ net.minecraft.w.m aa;
    public static final /* synthetic */ k b9;
    public static final /* synthetic */ k bC;
    public static final /* synthetic */ k ck;
    public static final /* synthetic */ k cC;
    public static final /* synthetic */ k L;

    private static k a(String string) {
        k k2 = net.minecraft.w.k.q.a(new v(string));
        if (k2 == null) {
            throw new IllegalStateException("Invalid Item requested: " + string);
        }
        return k2;
    }

    public static m[] b() {
        return cB;
    }

    static {
        if (net.minecraft.u.h.b() != null) {
            net.minecraft.u.h.b(new m[1]);
        }
        if (!net.minecraft.u.f.b()) {
            throw new RuntimeException("Accessed Items before Bootstrap!");
        }
        v = net.minecraft.u.h.a("air");
        u = net.minecraft.u.h.a("iron_shovel");
        aZ = net.minecraft.u.h.a("iron_pickaxe");
        cv = net.minecraft.u.h.a("iron_axe");
        cn = net.minecraft.u.h.a("flint_and_steel");
        ci = net.minecraft.u.h.a("apple");
        i = (H)net.minecraft.u.h.a("bow");
        x = net.minecraft.u.h.a("arrow");
        aA = net.minecraft.u.h.a("spectral_arrow");
        aI = net.minecraft.u.h.a("tipped_arrow");
        b4 = net.minecraft.u.h.a("coal");
        ag = net.minecraft.u.h.a("diamond");
        ad = net.minecraft.u.h.a("iron_ingot");
        I = net.minecraft.u.h.a("gold_ingot");
        bs = net.minecraft.u.h.a("iron_sword");
        bF = net.minecraft.u.h.a("wooden_sword");
        ac = net.minecraft.u.h.a("wooden_shovel");
        bo = net.minecraft.u.h.a("wooden_pickaxe");
        aS = net.minecraft.u.h.a("wooden_axe");
        cj = net.minecraft.u.h.a("stone_sword");
        bE = net.minecraft.u.h.a("stone_shovel");
        ai = net.minecraft.u.h.a("stone_pickaxe");
        k = net.minecraft.u.h.a("stone_axe");
        bN = net.minecraft.u.h.a("diamond_sword");
        al = net.minecraft.u.h.a("diamond_shovel");
        cm = net.minecraft.u.h.a("diamond_pickaxe");
        b9 = net.minecraft.u.h.a("diamond_axe");
        bz = net.minecraft.u.h.a("stick");
        z = net.minecraft.u.h.a("bowl");
        bb = net.minecraft.u.h.a("mushroom_stew");
        X = net.minecraft.u.h.a("golden_sword");
        b5 = net.minecraft.u.h.a("golden_shovel");
        bO = net.minecraft.u.h.a("golden_pickaxe");
        B = net.minecraft.u.h.a("golden_axe");
        aC = net.minecraft.u.h.a("string");
        bi = net.minecraft.u.h.a("feather");
        bZ = net.minecraft.u.h.a("gunpowder");
        bY = net.minecraft.u.h.a("wooden_hoe");
        bA = net.minecraft.u.h.a("stone_hoe");
        b6 = net.minecraft.u.h.a("iron_hoe");
        a2 = net.minecraft.u.h.a("diamond_hoe");
        e = net.minecraft.u.h.a("golden_hoe");
        a6 = net.minecraft.u.h.a("wheat_seeds");
        b1 = net.minecraft.u.h.a("wheat");
        cG = net.minecraft.u.h.a("bread");
        ab = (net.minecraft.w.m)net.minecraft.u.h.a("leather_helmet");
        cy = (net.minecraft.w.m)net.minecraft.u.h.a("leather_chestplate");
        E = (net.minecraft.w.m)net.minecraft.u.h.a("leather_leggings");
        K = (net.minecraft.w.m)net.minecraft.u.h.a("leather_boots");
        p = (net.minecraft.w.m)net.minecraft.u.h.a("chainmail_helmet");
        a4 = (net.minecraft.w.m)net.minecraft.u.h.a("chainmail_chestplate");
        H = (net.minecraft.w.m)net.minecraft.u.h.a("chainmail_leggings");
        b_ = (net.minecraft.w.m)net.minecraft.u.h.a("chainmail_boots");
        af = (net.minecraft.w.m)net.minecraft.u.h.a("iron_helmet");
        aK = (net.minecraft.w.m)net.minecraft.u.h.a("iron_chestplate");
        aa = (net.minecraft.w.m)net.minecraft.u.h.a("iron_leggings");
        D = (net.minecraft.w.m)net.minecraft.u.h.a("iron_boots");
        bD = (net.minecraft.w.m)net.minecraft.u.h.a("diamond_helmet");
        an = (net.minecraft.w.m)net.minecraft.u.h.a("diamond_chestplate");
        bv = (net.minecraft.w.m)net.minecraft.u.h.a("diamond_leggings");
        w = (net.minecraft.w.m)net.minecraft.u.h.a("diamond_boots");
        S = (net.minecraft.w.m)net.minecraft.u.h.a("golden_helmet");
        cF = (net.minecraft.w.m)net.minecraft.u.h.a("golden_chestplate");
        bP = (net.minecraft.w.m)net.minecraft.u.h.a("golden_leggings");
        cs = (net.minecraft.w.m)net.minecraft.u.h.a("golden_boots");
        aj = net.minecraft.u.h.a("flint");
        aP = net.minecraft.u.h.a("porkchop");
        cw = net.minecraft.u.h.a("cooked_porkchop");
        aR = net.minecraft.u.h.a("painting");
        bt = net.minecraft.u.h.a("golden_apple");
        bk = net.minecraft.u.h.a("sign");
        Q = net.minecraft.u.h.a("wooden_door");
        bd = net.minecraft.u.h.a("spruce_door");
        ao = net.minecraft.u.h.a("birch_door");
        cD = net.minecraft.u.h.a("jungle_door");
        ax = net.minecraft.u.h.a("acacia_door");
        cb = net.minecraft.u.h.a("dark_oak_door");
        P = net.minecraft.u.h.a("bucket");
        ah = net.minecraft.u.h.a("water_bucket");
        cg = net.minecraft.u.h.a("lava_bucket");
        q = net.minecraft.u.h.a("minecart");
        be = net.minecraft.u.h.a("saddle");
        cA = net.minecraft.u.h.a("iron_door");
        a7 = net.minecraft.u.h.a("redstone");
        aB = net.minecraft.u.h.a("snowball");
        N = net.minecraft.u.h.a("boat");
        Z = net.minecraft.u.h.a("spruce_boat");
        s = net.minecraft.u.h.a("birch_boat");
        U = net.minecraft.u.h.a("jungle_boat");
        R = net.minecraft.u.h.a("acacia_boat");
        O = net.minecraft.u.h.a("dark_oak_boat");
        aQ = net.minecraft.u.h.a("leather");
        n = net.minecraft.u.h.a("milk_bucket");
        by = net.minecraft.u.h.a("brick");
        ca = net.minecraft.u.h.a("clay_ball");
        co = net.minecraft.u.h.a("reeds");
        C = net.minecraft.u.h.a("paper");
        b8 = net.minecraft.u.h.a("book");
        bw = net.minecraft.u.h.a("slime_ball");
        aq = net.minecraft.u.h.a("chest_minecart");
        aE = net.minecraft.u.h.a("furnace_minecart");
        bB = net.minecraft.u.h.a("egg");
        b7 = net.minecraft.u.h.a("compass");
        bQ = (au)net.minecraft.u.h.a("fishing_rod");
        br = net.minecraft.u.h.a("clock");
        cr = net.minecraft.u.h.a("glowstone_dust");
        aw = net.minecraft.u.h.a("fish");
        cd = net.minecraft.u.h.a("cooked_fish");
        aL = net.minecraft.u.h.a("dye");
        bh = net.minecraft.u.h.a("bone");
        bm = net.minecraft.u.h.a("sugar");
        aW = net.minecraft.u.h.a("cake");
        bl = net.minecraft.u.h.a("bed");
        aY = net.minecraft.u.h.a("repeater");
        ae = net.minecraft.u.h.a("cookie");
        a9 = (an)net.minecraft.u.h.a("filled_map");
        aT = (aW)net.minecraft.u.h.a("shears");
        ap = net.minecraft.u.h.a("melon");
        bJ = net.minecraft.u.h.a("pumpkin_seeds");
        bu = net.minecraft.u.h.a("melon_seeds");
        aV = net.minecraft.u.h.a("beef");
        b2 = net.minecraft.u.h.a("cooked_beef");
        bp = net.minecraft.u.h.a("chicken");
        F = net.minecraft.u.h.a("cooked_chicken");
        h = net.minecraft.u.h.a("mutton");
        ct = net.minecraft.u.h.a("cooked_mutton");
        cz = net.minecraft.u.h.a("rabbit");
        bT = net.minecraft.u.h.a("cooked_rabbit");
        cu = net.minecraft.u.h.a("rabbit_stew");
        m = net.minecraft.u.h.a("rabbit_foot");
        bX = net.minecraft.u.h.a("rabbit_hide");
        ba = net.minecraft.u.h.a("rotten_flesh");
        o = net.minecraft.u.h.a("ender_pearl");
        bx = net.minecraft.u.h.a("blaze_rod");
        bK = net.minecraft.u.h.a("ghast_tear");
        bM = net.minecraft.u.h.a("gold_nugget");
        cl = net.minecraft.u.h.a("nether_wart");
        V = (ao)net.minecraft.u.h.a("potion");
        b3 = (ao)net.minecraft.u.h.a("splash_potion");
        W = (ao)net.minecraft.u.h.a("lingering_potion");
        ch = net.minecraft.u.h.a("glass_bottle");
        g = net.minecraft.u.h.a("dragon_breath");
        T = net.minecraft.u.h.a("spider_eye");
        ak = net.minecraft.u.h.a("fermented_spider_eye");
        cC = net.minecraft.u.h.a("blaze_powder");
        y = net.minecraft.u.h.a("magma_cream");
        c = net.minecraft.u.h.a("brewing_stand");
        a1 = net.minecraft.u.h.a("cauldron");
        cE = net.minecraft.u.h.a("ender_eye");
        bq = net.minecraft.u.h.a("speckled_melon");
        bn = net.minecraft.u.h.a("spawn_egg");
        bG = net.minecraft.u.h.a("experience_bottle");
        bL = net.minecraft.u.h.a("fire_charge");
        a5 = net.minecraft.u.h.a("writable_book");
        as = net.minecraft.u.h.a("written_book");
        aO = net.minecraft.u.h.a("emerald");
        L = net.minecraft.u.h.a("item_frame");
        cx = net.minecraft.u.h.a("flower_pot");
        aG = net.minecraft.u.h.a("carrot");
        f = net.minecraft.u.h.a("potato");
        bg = net.minecraft.u.h.a("baked_potato");
        bC = net.minecraft.u.h.a("poisonous_potato");
        Y = (aF)net.minecraft.u.h.a("map");
        aN = net.minecraft.u.h.a("golden_carrot");
        cp = net.minecraft.u.h.a("skull");
        bW = net.minecraft.u.h.a("carrot_on_a_stick");
        aF = net.minecraft.u.h.a("nether_star");
        ck = net.minecraft.u.h.a("pumpkin_pie");
        av = net.minecraft.u.h.a("fireworks");
        bS = net.minecraft.u.h.a("firework_charge");
        a0 = net.minecraft.u.h.a("enchanted_book");
        t = net.minecraft.u.h.a("comparator");
        b0 = net.minecraft.u.h.a("netherbrick");
        J = net.minecraft.u.h.a("quartz");
        l = net.minecraft.u.h.a("tnt_minecart");
        at = net.minecraft.u.h.a("hopper_minecart");
        d = (n)net.minecraft.u.h.a("armor_stand");
        a = net.minecraft.u.h.a("iron_horse_armor");
        bf = net.minecraft.u.h.a("golden_horse_armor");
        aD = net.minecraft.u.h.a("diamond_horse_armor");
        G = net.minecraft.u.h.a("lead");
        bc = net.minecraft.u.h.a("name_tag");
        aJ = net.minecraft.u.h.a("command_block_minecart");
        a3 = net.minecraft.u.h.a("record_13");
        bV = net.minecraft.u.h.a("record_cat");
        bI = net.minecraft.u.h.a("record_blocks");
        aX = net.minecraft.u.h.a("record_chirp");
        az = net.minecraft.u.h.a("record_far");
        bH = net.minecraft.u.h.a("record_mall");
        j = net.minecraft.u.h.a("record_mellohi");
        aH = net.minecraft.u.h.a("record_stal");
        aM = net.minecraft.u.h.a("record_strad");
        am = net.minecraft.u.h.a("record_ward");
        bU = net.minecraft.u.h.a("record_11");
        bj = net.minecraft.u.h.a("record_wait");
        ce = net.minecraft.u.h.a("prismarine_shard");
        M = net.minecraft.u.h.a("prismarine_crystals");
        aU = net.minecraft.u.h.a("banner");
        cc = net.minecraft.u.h.a("end_crystal");
        cq = net.minecraft.u.h.a("shield");
        cf = net.minecraft.u.h.a("elytra");
        au = net.minecraft.u.h.a("chorus_fruit");
        r = net.minecraft.u.h.a("chorus_fruit_popped");
        bR = net.minecraft.u.h.a("beetroot_seeds");
        b = net.minecraft.u.h.a("beetroot");
        a_ = net.minecraft.u.h.a("beetroot_soup");
        A = net.minecraft.u.h.a("totem_of_undying");
        ay = net.minecraft.u.h.a("shulker_shell");
        a8 = net.minecraft.u.h.a("iron_nugget");
        ar = net.minecraft.u.h.a("knowledge_book");
    }

    public static void b(m[] arrm) {
        cB = arrm;
    }

    private static IllegalStateException a(IllegalStateException illegalStateException) {
        return illegalStateException;
    }
}

